// STE-123 + STE-153 — `synthesizeAuditSection(claudeMdPath, resolvedSchemaLValues)` helper.
//
// Synthesizes the `## /setup audit` section from the in-scope resolved Schema L
// values table /setup populated during steps 7b/7c/7d. Each entry carries a
// per-resolution `reason:` string (`"user-supplied"` or `"default applied"`)
// so the audit section is a complete provenance log of every well-formed
// /setup run, not only of default-applied outcomes (STE-153). Idempotent —
// existing entries are preserved verbatim per STE-108's append-only contract.

import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  AuditPostconditionUnsatisfiable,
  synthesizeAuditSection,
  type ResolvedSchemaLValues,
} from "./synthesize_audit";

const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

function tmpClaudeMd(initial: string): { path: string; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), "synthesize-audit-"));
  const path = join(dir, "CLAUDE.md");
  writeFileSync(path, initial);
  return { path, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

function fullDefaults(): ResolvedSchemaLValues {
  return {
    date: "2026-04-27",
    branchTemplate: { value: "{type}/{ticket-id}-{slug}", reason: "default applied" },
    docsUserFacing: { value: false, reason: "default applied" },
    docsPackages: { value: false, reason: "default applied" },
    docsChangelogCi: { value: false, reason: "default applied" },
  };
}

describe("synthesizeAuditSection — happy path (AC-STE-123.2)", () => {
  test("section absent + 4 defaults applied → 4 entries synthesized", () => {
    const initial = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "branch_template: {type}/{ticket-id}-{slug}",
      "",
      "## Docs",
      "",
      "user_facing_mode: false",
      "packages_mode: false",
      "changelog_ci_owned: false",
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const r = synthesizeAuditSection(ctx.path, fullDefaults());
      expect(r.synthesized).toBe(4);
      expect(r.skipped).toBe(0);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toMatch(/## \/setup audit/);
      expect(out).toMatch(/step:7c \(branch_template\) value:"{type}\/{ticket-id}-{slug}"/);
      expect(out).toMatch(/step:7d \(docs\.user_facing_mode\) value:false/);
      expect(out).toMatch(/step:7d \(docs\.packages_mode\) value:false/);
      expect(out).toMatch(/step:7d \(docs\.changelog_ci_owned\) value:false/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — idempotent (AC-STE-123.3)", () => {
  test("section partial (1 of 4 already present) → 3 entries synthesized, 1 skipped", () => {
    const initial = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "",
      "## /setup audit",
      "",
      `- 2026-04-27 step:7c (branch_template) value:"{type}/{ticket-id}-{slug}" reason:"default applied"`,
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const r = synthesizeAuditSection(ctx.path, fullDefaults());
      expect(r.synthesized).toBe(3);
      expect(r.skipped).toBe(1);
      const out = readFileSync(ctx.path, "utf-8");
      // Original entry preserved verbatim.
      expect(
        out.match(/step:7c \(branch_template\) value:"{type}\/{ticket-id}-{slug}"/g)?.length,
      ).toBe(1);
    } finally {
      ctx.cleanup();
    }
  });

  test("section complete (all entries present) → no-op (0 synthesized, 4 skipped)", () => {
    const initial = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## /setup audit",
      "",
      `- 2026-04-27 step:7c (branch_template) value:"{type}/{ticket-id}-{slug}" reason:"default applied"`,
      `- 2026-04-27 step:7d (docs.user_facing_mode) value:false reason:"default applied"`,
      `- 2026-04-27 step:7d (docs.packages_mode) value:false reason:"default applied"`,
      `- 2026-04-27 step:7d (docs.changelog_ci_owned) value:false reason:"default applied"`,
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const r = synthesizeAuditSection(ctx.path, fullDefaults());
      expect(r.synthesized).toBe(0);
      expect(r.skipped).toBe(4);
      const after = readFileSync(ctx.path, "utf-8");
      expect(after).toBe(initial); // byte-identical when no synthesis fires
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — refusal path (AC-STE-123.4)", () => {
  test("empty resolvedSchemaLValues table throws AuditPostconditionUnsatisfiable", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const empty: ResolvedSchemaLValues = { date: "2026-04-27" };
      expect(() => synthesizeAuditSection(ctx.path, empty)).toThrow(
        AuditPostconditionUnsatisfiable,
      );
      expect(() => synthesizeAuditSection(ctx.path, empty)).toThrow(/resolved Schema L values/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — escape rules (AC-STE-123.7)", () => {
  test("em-dash branch_template value round-trips byte-identically", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const defaults: ResolvedSchemaLValues = {
        date: "2026-04-27",
        branchTemplate: { value: "feat/{ticket-id}-—-{slug}", reason: "default applied" },
      };
      synthesizeAuditSection(ctx.path, defaults);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toContain('value:"feat/{ticket-id}-—-{slug}"');
    } finally {
      ctx.cleanup();
    }
  });

  test("reason string with embedded double-quote escapes via JSON.stringify", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const defaults: ResolvedSchemaLValues = {
        date: "2026-04-27",
        branchTemplate: { value: "x", reason: 'has "quotes" inside' },
      };
      synthesizeAuditSection(ctx.path, defaults);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toContain(`reason:"has \\"quotes\\" inside"`);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — option-5 fixture (AC-STE-123.6)", () => {
  test("option-5 reproducer: pre-existing CLAUDE.md merged with defaults → audit synthesized", () => {
    // Mirrors smoke-test 2026-04-27 run #3: existing file carries Task Tracking
    // and Docs, no toolkit marker; /setup adds marker + applies defaults +
    // runs step 8a.
    const initial = [
      TOOLKIT_MARKER, // /setup added the marker first
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "mcp_server: linear",
      "",
      "### Linear",
      "",
      "team: STE",
      "project: DPT — Dev Process Toolkit",
      "",
      "## Docs",
      "",
      "user_facing_mode: false",
      "packages_mode: false",
      "changelog_ci_owned: false",
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const r = synthesizeAuditSection(ctx.path, fullDefaults());
      expect(r.synthesized).toBe(4);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toMatch(/## \/setup audit/);
      // Probe-19 trigger conditions met (Docs + branch_template upstream of audit section).
      expect(out).toContain("## /setup audit");
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — partial defaults", () => {
  test("only branchTemplate provided → 1 entry synthesized", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const defaults: ResolvedSchemaLValues = {
        date: "2026-04-27",
        branchTemplate: { value: "feat/{ticket-id}-{slug}", reason: "default applied" },
      };
      const r = synthesizeAuditSection(ctx.path, defaults);
      expect(r.synthesized).toBe(1);
      expect(r.skipped).toBe(0);
    } finally {
      ctx.cleanup();
    }
  });

  test("only docs flags (no branchTemplate) → 3 entries synthesized", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const defaults: ResolvedSchemaLValues = {
        date: "2026-04-27",
        docsUserFacing: { value: true, reason: "user said yes" },
        docsPackages: { value: false, reason: "default applied" },
        docsChangelogCi: { value: false, reason: "default applied" },
      };
      const r = synthesizeAuditSection(ctx.path, defaults);
      expect(r.synthesized).toBe(3);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — STE-153 user-supplied provenance (AC-STE-153.1)", () => {
  test("all four entries with reason: \"user-supplied\" → 4 synthesized, each carries the user-supplied reason", () => {
    const initial = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "branch_template: feat/{ticket-id}-{slug}",
      "",
      "## Docs",
      "",
      "user_facing_mode: true",
      "packages_mode: true",
      "changelog_ci_owned: true",
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const allUserSupplied: ResolvedSchemaLValues = {
        date: "2026-04-29",
        branchTemplate: { value: "feat/{ticket-id}-{slug}", reason: "user-supplied" },
        docsUserFacing: { value: true, reason: "user-supplied" },
        docsPackages: { value: true, reason: "user-supplied" },
        docsChangelogCi: { value: true, reason: "user-supplied" },
      };
      const r = synthesizeAuditSection(ctx.path, allUserSupplied);
      expect(r.synthesized).toBe(4);
      expect(r.skipped).toBe(0);
      const out = readFileSync(ctx.path, "utf-8");
      // All four bullets carry the user-supplied reason — no "default applied" present.
      const userSuppliedMatches = out.match(/reason:"user-supplied"/g);
      expect(userSuppliedMatches?.length).toBe(4);
      expect(out.includes(`reason:"default applied"`)).toBe(false);
      // Field-level coverage.
      expect(out).toMatch(/step:7c \(branch_template\) value:"feat\/{ticket-id}-{slug}" reason:"user-supplied"/);
      expect(out).toMatch(/step:7d \(docs\.user_facing_mode\) value:true reason:"user-supplied"/);
      expect(out).toMatch(/step:7d \(docs\.packages_mode\) value:true reason:"user-supplied"/);
      expect(out).toMatch(/step:7d \(docs\.changelog_ci_owned\) value:true reason:"user-supplied"/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — STE-153 mixed provenance (AC-STE-153.3)", () => {
  test("branchTemplate user-supplied + docs.* default applied → per-entry reason preserved", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const mixed: ResolvedSchemaLValues = {
        date: "2026-04-29",
        branchTemplate: { value: "fix/{ticket-id}", reason: "user-supplied" },
        docsUserFacing: { value: false, reason: "default applied" },
        docsPackages: { value: false, reason: "default applied" },
        docsChangelogCi: { value: false, reason: "default applied" },
      };
      const r = synthesizeAuditSection(ctx.path, mixed);
      expect(r.synthesized).toBe(4);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toMatch(/step:7c \(branch_template\) value:"fix\/{ticket-id}" reason:"user-supplied"/);
      expect(out).toMatch(/step:7d \(docs\.user_facing_mode\) value:false reason:"default applied"/);
      expect(out).toMatch(/step:7d \(docs\.packages_mode\) value:false reason:"default applied"/);
      expect(out).toMatch(/step:7d \(docs\.changelog_ci_owned\) value:false reason:"default applied"/);
      // Both reasons present — provenance is per-resolution, not per-run.
      expect(out.match(/reason:"user-supplied"/g)?.length).toBe(1);
      expect(out.match(/reason:"default applied"/g)?.length).toBe(3);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — STE-153 idempotent on conflicting reason (AC-STE-153.3)", () => {
  test("re-run with a different reason for the same (step, field) is a skip — original entry preserved verbatim", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      // First call: branch_template recorded with reason: "default applied".
      const firstRun: ResolvedSchemaLValues = {
        date: "2026-04-29",
        branchTemplate: { value: "feat/{ticket-id}-{slug}", reason: "default applied" },
      };
      const r1 = synthesizeAuditSection(ctx.path, firstRun);
      expect(r1.synthesized).toBe(1);
      expect(r1.skipped).toBe(0);

      // Second call: same (step, field) but reason: "user-supplied". Dedup
      // is on (step, field) only — the second call is a skip, not an
      // overwrite, preserving STE-108 append-only semantics.
      const secondRun: ResolvedSchemaLValues = {
        date: "2026-04-29",
        branchTemplate: { value: "feat/{ticket-id}-{slug}", reason: "user-supplied" },
      };
      const r2 = synthesizeAuditSection(ctx.path, secondRun);
      expect(r2.synthesized).toBe(0);
      expect(r2.skipped).toBe(1);

      const out = readFileSync(ctx.path, "utf-8");
      // Only one entry for (step:7c, branch_template), and it carries the
      // ORIGINAL reason — second call did not overwrite.
      const branchTemplateMatches = out.match(/step:7c \(branch_template\)/g);
      expect(branchTemplateMatches?.length).toBe(1);
      expect(out).toContain(`step:7c (branch_template) value:"feat/{ticket-id}-{slug}" reason:"default applied"`);
      expect(out).not.toContain(`step:7c (branch_template) value:"feat/{ticket-id}-{slug}" reason:"user-supplied"`);
    } finally {
      ctx.cleanup();
    }
  });
});
