// STE-378 AC-STE-378.4 — `token_stats.enabled` audit row synthesis.
//
// `synthesizeAuditSection` must emit a `token_stats.enabled` row alongside
// the three `docs.<flag>` rows when the resolved Schema L values table
// carries a `tokenStatsEnabled` entry, of the shape
//   step:<n> (token_stats.enabled) value:<bool> reason:"<user-supplied|default applied>"
// and dedup on the `${step}:token_stats.enabled` key so a re-run is a skip,
// not a double-write. Mirrors the docs.<flag> provenance rows.

import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  synthesizeAuditSection,
  type ResolvedSchemaLValues,
} from "./synthesize_audit";

const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

function tmpClaudeMd(initial: string): { path: string; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), "synthesize-audit-tokenstats-"));
  const path = join(dir, "CLAUDE.md");
  writeFileSync(path, initial);
  return { path, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

describe("synthesizeAuditSection — token_stats.enabled row (AC-STE-378.4)", () => {
  test("tokenStatsEnabled: true / user-supplied → a token_stats.enabled row is synthesized", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const resolved: ResolvedSchemaLValues = {
        date: "2026-07-10",
        docsUserFacing: { value: false, reason: "default applied" },
        tokenStatsEnabled: { value: true, reason: "user-supplied" },
      };
      synthesizeAuditSection(ctx.path, resolved);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toMatch(
        /step:\S+ \(token_stats\.enabled\) value:true reason:"user-supplied"/,
      );
    } finally {
      ctx.cleanup();
    }
  });

  test("tokenStatsEnabled: false / default applied → value:false reason:\"default applied\"", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const resolved: ResolvedSchemaLValues = {
        date: "2026-07-10",
        docsUserFacing: { value: false, reason: "default applied" },
        tokenStatsEnabled: { value: false, reason: "default applied" },
      };
      synthesizeAuditSection(ctx.path, resolved);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toMatch(
        /step:\S+ \(token_stats\.enabled\) value:false reason:"default applied"/,
      );
    } finally {
      ctx.cleanup();
    }
  });

  test("re-run is idempotent — dedup on `${step}:token_stats.enabled` keeps exactly one row", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const resolved: ResolvedSchemaLValues = {
        date: "2026-07-10",
        tokenStatsEnabled: { value: true, reason: "user-supplied" },
      };
      const r1 = synthesizeAuditSection(ctx.path, resolved);
      expect(r1.synthesized).toBe(1);
      expect(r1.skipped).toBe(0);

      // Second call: same (step, token_stats.enabled) — a skip, not an
      // overwrite. Append-only semantics preserved.
      const r2 = synthesizeAuditSection(ctx.path, resolved);
      expect(r2.synthesized).toBe(0);
      expect(r2.skipped).toBe(1);

      const out = readFileSync(ctx.path, "utf-8");
      expect(out.match(/\(token_stats\.enabled\)/g)?.length).toBe(1);
    } finally {
      ctx.cleanup();
    }
  });
});
