// STE-123 — `synthesizeAuditSection(claudeMdPath, resolvedDefaults)` helper.
//
// Synthesizes the `## /setup audit` section from the in-scope resolved-defaults
// table /setup populated during steps 7b/7c/7d. Idempotent — existing entries
// are preserved verbatim per STE-108's append-only contract.

import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  AuditPostconditionUnsatisfiable,
  synthesizeAuditSection,
  type ResolvedDefaults,
} from "./synthesize_audit";

const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

function tmpClaudeMd(initial: string): { path: string; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), "synthesize-audit-"));
  const path = join(dir, "CLAUDE.md");
  writeFileSync(path, initial);
  return { path, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

function fullDefaults(): ResolvedDefaults {
  return {
    date: "2026-04-27",
    branchTemplate: { value: "{type}/{ticket-id}-{slug}", reason: "default applied" },
    docsUserFacing: { value: false, reason: "default applied" },
    docsPackages: { value: false, reason: "default applied" },
    docsChangelogCi: { value: false, reason: "default applied" },
  };
}

describe("synthesizeAuditSection — happy path (AC-STE-123.2)", () => {
  test("section absent + 4 defaults applied → 4 entries synthesized", () => {
    const initial = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "branch_template: {type}/{ticket-id}-{slug}",
      "",
      "## Docs",
      "",
      "user_facing_mode: false",
      "packages_mode: false",
      "changelog_ci_owned: false",
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const r = synthesizeAuditSection(ctx.path, fullDefaults());
      expect(r.synthesized).toBe(4);
      expect(r.skipped).toBe(0);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toMatch(/## \/setup audit/);
      expect(out).toMatch(/step:7c \(branch_template\) value:"{type}\/{ticket-id}-{slug}"/);
      expect(out).toMatch(/step:7d \(docs\.user_facing_mode\) value:false/);
      expect(out).toMatch(/step:7d \(docs\.packages_mode\) value:false/);
      expect(out).toMatch(/step:7d \(docs\.changelog_ci_owned\) value:false/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — idempotent (AC-STE-123.3)", () => {
  test("section partial (1 of 4 already present) → 3 entries synthesized, 1 skipped", () => {
    const initial = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "",
      "## /setup audit",
      "",
      `- 2026-04-27 step:7c (branch_template) value:"{type}/{ticket-id}-{slug}" reason:"default applied"`,
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const r = synthesizeAuditSection(ctx.path, fullDefaults());
      expect(r.synthesized).toBe(3);
      expect(r.skipped).toBe(1);
      const out = readFileSync(ctx.path, "utf-8");
      // Original entry preserved verbatim.
      expect(
        out.match(/step:7c \(branch_template\) value:"{type}\/{ticket-id}-{slug}"/g)?.length,
      ).toBe(1);
    } finally {
      ctx.cleanup();
    }
  });

  test("section complete (all entries present) → no-op (0 synthesized, 4 skipped)", () => {
    const initial = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## /setup audit",
      "",
      `- 2026-04-27 step:7c (branch_template) value:"{type}/{ticket-id}-{slug}" reason:"default applied"`,
      `- 2026-04-27 step:7d (docs.user_facing_mode) value:false reason:"default applied"`,
      `- 2026-04-27 step:7d (docs.packages_mode) value:false reason:"default applied"`,
      `- 2026-04-27 step:7d (docs.changelog_ci_owned) value:false reason:"default applied"`,
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const r = synthesizeAuditSection(ctx.path, fullDefaults());
      expect(r.synthesized).toBe(0);
      expect(r.skipped).toBe(4);
      const after = readFileSync(ctx.path, "utf-8");
      expect(after).toBe(initial); // byte-identical when no synthesis fires
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — refusal path (AC-STE-123.4)", () => {
  test("empty resolvedDefaults table throws AuditPostconditionUnsatisfiable", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const empty: ResolvedDefaults = { date: "2026-04-27" };
      expect(() => synthesizeAuditSection(ctx.path, empty)).toThrow(
        AuditPostconditionUnsatisfiable,
      );
      expect(() => synthesizeAuditSection(ctx.path, empty)).toThrow(/resolved-defaults/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — escape rules (AC-STE-123.7)", () => {
  test("em-dash branch_template value round-trips byte-identically", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const defaults: ResolvedDefaults = {
        date: "2026-04-27",
        branchTemplate: { value: "feat/{ticket-id}-—-{slug}", reason: "default applied" },
      };
      synthesizeAuditSection(ctx.path, defaults);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toContain('value:"feat/{ticket-id}-—-{slug}"');
    } finally {
      ctx.cleanup();
    }
  });

  test("reason string with embedded double-quote escapes via JSON.stringify", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const defaults: ResolvedDefaults = {
        date: "2026-04-27",
        branchTemplate: { value: "x", reason: 'has "quotes" inside' },
      };
      synthesizeAuditSection(ctx.path, defaults);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toContain(`reason:"has \\"quotes\\" inside"`);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — option-5 fixture (AC-STE-123.6)", () => {
  test("option-5 reproducer: pre-existing CLAUDE.md merged with defaults → audit synthesized", () => {
    // Mirrors smoke-test 2026-04-27 run #3: existing file carries Task Tracking
    // and Docs, no toolkit marker; /setup adds marker + applies defaults +
    // runs step 8a.
    const initial = [
      TOOLKIT_MARKER, // /setup added the marker first
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "mcp_server: linear",
      "",
      "### Linear",
      "",
      "team: STE",
      "project: DPT — Dev Process Toolkit",
      "",
      "## Docs",
      "",
      "user_facing_mode: false",
      "packages_mode: false",
      "changelog_ci_owned: false",
      "",
    ].join("\n");
    const ctx = tmpClaudeMd(initial);
    try {
      const r = synthesizeAuditSection(ctx.path, fullDefaults());
      expect(r.synthesized).toBe(4);
      const out = readFileSync(ctx.path, "utf-8");
      expect(out).toMatch(/## \/setup audit/);
      // Probe-19 trigger conditions met (Docs + branch_template upstream of audit section).
      expect(out).toContain("## /setup audit");
    } finally {
      ctx.cleanup();
    }
  });
});

describe("synthesizeAuditSection — partial defaults", () => {
  test("only branchTemplate provided → 1 entry synthesized", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const defaults: ResolvedDefaults = {
        date: "2026-04-27",
        branchTemplate: { value: "feat/{ticket-id}-{slug}", reason: "default applied" },
      };
      const r = synthesizeAuditSection(ctx.path, defaults);
      expect(r.synthesized).toBe(1);
      expect(r.skipped).toBe(0);
    } finally {
      ctx.cleanup();
    }
  });

  test("only docs flags (no branchTemplate) → 3 entries synthesized", () => {
    const ctx = tmpClaudeMd(`${TOOLKIT_MARKER}\n\n# Project\n`);
    try {
      const defaults: ResolvedDefaults = {
        date: "2026-04-27",
        docsUserFacing: { value: true, reason: "user said yes" },
        docsPackages: { value: false, reason: "default applied" },
        docsChangelogCi: { value: false, reason: "default applied" },
      };
      const r = synthesizeAuditSection(ctx.path, defaults);
      expect(r.synthesized).toBe(3);
    } finally {
      ctx.cleanup();
    }
  });
});
