import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Regression guard for STE-68 AC-STE-68.6 — `templates/CLAUDE.md.template`
// carries a commented-out `## Docs` stub that advertises the three Schema-L
// keys downstream projects configure via `/setup` Step 7d.
//
// Rationale mirrors `gate-check-branch-template-hygiene.test.ts` (STE-64
// AC-STE-64.12): the template is the advertisement. If the stub silently
// drops out, downstream projects generated by `/setup` still default to
// all-false (AC-STE-68.3 backward-compat) but the user never learns the
// three keys exist, and `/docs` becomes a silent no-op.

const pluginRoot = join(import.meta.dir, "..");
const templatePath = join(pluginRoot, "templates", "CLAUDE.md.template");

describe("STE-68 AC-STE-68.6 — CLAUDE.md.template documents the ## Docs keys", () => {
  test("template file contains all three documented keys", () => {
    const body = readFileSync(templatePath, "utf-8");
    expect(body).toContain("user_facing_mode:");
    expect(body).toContain("packages_mode:");
    expect(body).toContain("changelog_ci_owned:");
  });

  test("the canonical one-line pointer is present (AC-STE-68.6 wording)", () => {
    const body = readFileSync(templatePath, "utf-8");
    expect(body).toContain(
      "<!-- /setup fills this section; absent section ≡ all three false -->",
    );
  });

  test("the stub is commented so readDocsConfig does not pick it up as a live section", () => {
    const body = readFileSync(templatePath, "utf-8");
    const lines = body.split("\n");
    // Mirrors the readDocsConfig probe: find a line literally equal to
    // "## Docs". The template must not contain one — otherwise the live
    // grep-probe would treat the commented stub as the real section.
    const liveHeadingIdx = lines.findIndex((l) => l === "## Docs");
    expect(liveHeadingIdx).toBe(-1);
  });
});
