import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  hasDefaultApplicableOutcomes,
  runSetupAuditSectionPresenceProbe,
} from "../adapters/_shared/src/setup_audit_section_presence";

// STE-108 AC-STE-108.6 — `setup-audit-section-presence` /gate-check probe.
//
// Trigger: CLAUDE.md is toolkit-managed (carries the `<!-- generated by
// /dev-process-toolkit:setup -->` marker) AND a default-applied step
// outcome is detectable in the file (Schema L `branch_template:` /
// `## Docs` flags). Then the `## /setup audit` section MUST exist.
//
// Five fixtures via mkdtempSync:
//   (a) hand-written CLAUDE.md (no marker) → vacuous pass
//   (b) toolkit-managed + audit section present → pass
//   (c) toolkit-managed + audit section absent → fail
//   (d) toolkit-managed + no Schema L / Docs (interactive run with no defaults) → vacuous pass
//   (e) absent CLAUDE.md → vacuous pass

const pluginRoot = join(import.meta.dir, "..");

const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

function makeProject(claudeMdContent: string | null): { root: string; cleanup: () => void } {
  const root = mkdtempSync(join(tmpdir(), "audit-section-probe-"));
  if (claudeMdContent !== null) {
    writeFileSync(join(root, "CLAUDE.md"), claudeMdContent);
  }
  return { root, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

describe("AC-STE-108.6(a) hand-written CLAUDE.md → vacuous pass", () => {
  test("no toolkit marker → probe is vacuous (no violations)", async () => {
    const ctx = makeProject(`# My Project\n\nA hand-written CLAUDE.md.\n\n## Task Tracking\n\nmode: linear\nbranch_template: feat/{ticket-id}\n`);
    try {
      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-108.6(b) toolkit-managed + audit section present → pass", () => {
  test("audit section present satisfies the contract", async () => {
    const body = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "branch_template: feat/{ticket-id}-{slug}",
      "",
      "## /setup audit",
      "",
      `- 2026-04-25 step:7c (branch_template) value:"feat/{ticket-id}-{slug}" reason:"default applied"`,
      "",
    ].join("\n");
    const ctx = makeProject(body);
    try {
      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-108.6(c) toolkit-managed + audit section absent → fail", () => {
  test("missing audit section flags violation in NFR-10 canonical shape", async () => {
    const body = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "branch_template: feat/{ticket-id}-{slug}",
      "",
    ].join("\n");
    const ctx = makeProject(body);
    try {
      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      const v = report.violations[0]!;
      expect(v.note).toMatch(/CLAUDE\.md:\d+ — /);
      expect(v.note).toMatch(/setup audit/);
      expect(v.message).toMatch(/Remedy:/);
      expect(v.message).toMatch(/Context:/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-108.6(d) toolkit-managed + no defaults emitted → vacuous pass", () => {
  test("no Schema L branch_template AND no Docs section → vacuous pass", async () => {
    // Toolkit marker present but the user answered every question
    // interactively, so there are no default-applied artifacts to require
    // an audit entry for.
    const body = [TOOLKIT_MARKER, "", "# Project", "", "Body.", ""].join("\n");
    const ctx = makeProject(body);
    try {
      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-108.6(e) CLAUDE.md absent → vacuous pass", () => {
  test("no CLAUDE.md → no violations (project not toolkit-managed)", async () => {
    const ctx = makeProject(null);
    try {
      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-108.6 — gate-check SKILL.md prose declares the probe", () => {
  const gateCheckSkill = readFileSync(
    join(pluginRoot, "skills", "gate-check", "SKILL.md"),
    "utf-8",
  );
  test("SKILL.md references probe `setup-audit-section-presence`", () => {
    expect(gateCheckSkill).toMatch(/setup-audit-section-presence/);
  });
});

describe("AC-STE-123.1 — hasDefaultApplicableOutcomes is exported for cross-module reuse", () => {
  test("returns true when branch_template: line is populated", () => {
    expect(
      hasDefaultApplicableOutcomes("## Task Tracking\n\nbranch_template: feat/{ticket-id}\n"),
    ).toBe(true);
  });

  test("returns true when ## Docs heading is present", () => {
    expect(
      hasDefaultApplicableOutcomes("# Project\n\n## Docs\n\nuser_facing_mode: false\n"),
    ).toBe(true);
  });

  test("returns false on a hand-written file with neither trigger", () => {
    expect(hasDefaultApplicableOutcomes("# Project\n\nBody.\n")).toBe(false);
  });
});

describe("STE-123 — /setup SKILL.md prose declares step 8a", () => {
  const setupSkill = readFileSync(join(pluginRoot, "skills", "setup", "SKILL.md"), "utf-8");
  test("setup SKILL.md references step 8a Audit-section post-condition", () => {
    expect(setupSkill).toMatch(/### 8a\..*Audit-section post-condition/);
    expect(setupSkill).toMatch(/synthesizeAuditSection/);
    expect(setupSkill).toMatch(/hasDefaultApplicableOutcomes/);
    expect(setupSkill).toMatch(/STE-123/);
  });
});
