import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runBunZeroMatchPlaceholderProbe } from "../adapters/_shared/src/bun_zero_match_placeholder";

// STE-113 AC-STE-113.4 / AC-STE-113.5 — `bun-zero-match-placeholder` probe.
//
// Bun's `bun test` exits 1 when no test files match — kills the very first
// gate check on a fresh Bun project. The recommended workaround is a
// placeholder test file with a marker comment. The probe enforces:
//
//   if bun.lock exists AND no *.test.ts files exist (excluding node_modules)
//   AND no source file carries the marker comment "Bun zero-match workaround"
//   → fail.
//
// Four fixtures (per AC-STE-113.5):
//   (a) Bun project with no tests + no placeholder → fail
//   (b) Bun project with placeholder marker → pass
//   (c) Bun project with a real *.test.ts → pass
//   (d) Non-Bun project (no bun.lock) → vacuous pass

const pluginRoot = join(import.meta.dir, "..");

const MARKER = "// generated by /dev-process-toolkit:setup — Bun zero-match workaround (see examples/bun-typescript.md)";

function makeProject(opts: {
  bunLock?: boolean;
  placeholder?: { path: string; content: string } | null;
  realTest?: { path: string; content: string } | null;
}): { root: string; cleanup: () => void } {
  const root = mkdtempSync(join(tmpdir(), "bun-zero-match-"));
  if (opts.bunLock) writeFileSync(join(root, "bun.lock"), "{}\n");
  if (opts.placeholder) {
    const dir = join(root, opts.placeholder.path.split("/").slice(0, -1).join("/"));
    if (dir) mkdirSync(dir, { recursive: true });
    writeFileSync(join(root, opts.placeholder.path), opts.placeholder.content);
  }
  if (opts.realTest) {
    const dir = join(root, opts.realTest.path.split("/").slice(0, -1).join("/"));
    if (dir) mkdirSync(dir, { recursive: true });
    writeFileSync(join(root, opts.realTest.path), opts.realTest.content);
  }
  return { root, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

describe("AC-STE-113.5(a) Bun + no tests + no placeholder → fail", () => {
  test("violation names bun.lock + missing marker, includes remedy", async () => {
    const ctx = makeProject({ bunLock: true });
    try {
      const report = await runBunZeroMatchPlaceholderProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      const v = report.violations[0]!;
      expect(v.note).toMatch(/bun\.lock/);
      expect(v.note).toMatch(/zero-match|placeholder/i);
      expect(v.message).toMatch(/Remedy:/);
      expect(v.message).toMatch(/Context:/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-113.5(b) Bun + placeholder marker present → pass", () => {
  test("placeholder file with marker satisfies the contract", async () => {
    const ctx = makeProject({
      bunLock: true,
      placeholder: {
        path: "tests/.placeholder.test.ts",
        content: `${MARKER}\nimport { test } from "bun:test";\ntest("placeholder", () => {});\n`,
      },
    });
    try {
      const report = await runBunZeroMatchPlaceholderProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-113.5(c) Bun + real *.test.ts → pass", () => {
  test("real test file (no marker needed) → no violations", async () => {
    const ctx = makeProject({
      bunLock: true,
      realTest: {
        path: "tests/real_thing.test.ts",
        content: `import { test, expect } from "bun:test";\ntest("real", () => { expect(1+1).toBe(2); });\n`,
      },
    });
    try {
      const report = await runBunZeroMatchPlaceholderProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-113.5(d) non-Bun project → vacuous pass", () => {
  test("no bun.lock → probe is vacuous", async () => {
    const ctx = makeProject({ bunLock: false });
    try {
      const report = await runBunZeroMatchPlaceholderProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });

  test("non-Bun project even with no tests → vacuous pass", async () => {
    const ctx = makeProject({ bunLock: false });
    try {
      const report = await runBunZeroMatchPlaceholderProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-113.4 — gate-check SKILL.md prose declares the probe", () => {
  const gateCheckSkill = readFileSync(
    join(pluginRoot, "skills", "gate-check", "SKILL.md"),
    "utf-8",
  );
  test("SKILL.md references probe `bun-zero-match-placeholder`", () => {
    expect(gateCheckSkill).toMatch(/bun-zero-match-placeholder/);
  });
});

describe("AC-STE-113.1 — examples/bun-typescript.md exists with the four sections", () => {
  const examplePath = join(pluginRoot, "examples", "bun-typescript.md");
  const example = readFileSync(examplePath, "utf-8");

  test("file documents the zero-match-exit-1 behavior", () => {
    expect(example).toMatch(/zero-match|exit\s*1/i);
  });

  test("file documents the marker-comment workaround", () => {
    expect(example).toMatch(/Bun zero-match workaround/);
  });

  test("file lists the gate command `bunx tsc --noEmit && bun test`", () => {
    expect(example).toMatch(/bunx tsc --noEmit\s*&&\s*bun test/);
  });

  test("file references the canonical Bun permissions row", () => {
    expect(example).toMatch(/permissions\.json/);
    expect(example).toMatch(/bun \*|Bash\(bun \*\)/);
  });
});
