import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Doc-hygiene regression guard for STE-64 AC-STE-64.12.
//
// `/gate-check` probe #10 asserts at runtime that `templates/CLAUDE.md.template`
// documents the `branch_template:` Schema L key. If the key silently drops out
// of the template, downstream projects generated by `/setup` would have branch
// automation silently disabled (the AC-STE-64.1 "absent ⇒ disabled" backward-
// compat rule reads correctly in prose but the user never learns the key
// exists). This test is the backing regression canary — equivalent to the
// runtime grep the probe runs, but exercised inside the test suite.

const pluginRoot = join(import.meta.dir, "..");
const templatePath = join(pluginRoot, "templates", "CLAUDE.md.template");

describe("STE-64 AC-STE-64.12 — CLAUDE.md.template documents branch_template:", () => {
  test("template file contains the literal substring `branch_template:`", () => {
    const body = readFileSync(templatePath, "utf-8");
    expect(body).toContain("branch_template:");
  });

  test("template's branch_template: documentation names both template forms (AC-STE-388.2)", () => {
    // AC-STE-64.1's original default-for-mode split was retired by
    // AC-STE-388.2: `{type}/m{N}-{slug}` is now the single seeded default in
    // both modes, and `{type}/{ticket-id}-{slug}` survives only as the
    // milestone-less derivation fallback + customization example. Both forms
    // must stay discoverable in the template — the m-form because it is the
    // seeded default, the ticket form because operators overriding
    // `branch_template:` (and milestone-less FR runs) still resolve it.
    // `/gate-check` probe #10 (AC-STE-64.12) only catches a zero-match grep;
    // this test enforces the stronger both-forms invariant.
    const body = readFileSync(templatePath, "utf-8");
    expect(body).toContain("{type}/m{N}-{slug}");
    expect(body).toContain("{type}/{ticket-id}-{slug}");
  });
});

describe("AC-STE-139.5 — branch-template-hygiene runs clean on this repo's baseline", () => {
  test("the live repo's CLAUDE.md.template documents branch_template: (probe #10 grep)", () => {
    const body = readFileSync(templatePath, "utf-8");
    expect(body).toContain("branch_template:");
  });
});
