// M109 STE-394 — /gate-check probe `upgrade_staleness` (probe #69).
//
// A warn-only probe that walks the migration registry's detectors and reports
// every consumer artifact that has fallen behind current toolkit conventions.
// It never fails the gate: pre-existing drift must not block a merge.
//
// AC map:
//   AC-STE-394.1 — Step 0 applicability short-circuit (no toolkit-managed
//                  CLAUDE.md section ⇒ zero rows, ZERO detectors walked), then
//                  a registry-order detector walk; one row per `applies: true`
//                  entry, rendered under GATE PASSED WITH NOTES. Never FAILED.
//   AC-STE-394.2 — byte-pinned row shape
//                  `<entry-id> (<introduced_in>): <evidence joined by "; ">`,
//                  evidence in the detector's returned order, never re-sorted,
//                  never truncated.
//   AC-STE-394.3 — purity: pure file reads + a registry module load. No git,
//                  no network, no LLM judgment, no writes.
//   AC-STE-394.4 — vacuous in both directions, including the consumer-safety
//                  case: legacy artifacts on disk + no toolkit-managed
//                  CLAUDE.md section ⇒ zero rows and no error.
//   AC-STE-394.5 — the NOTES block closes with the byte-pinned remedy literal,
//                  exactly once with >= 1 row, never with zero rows.
//   AC-STE-394.9 — non-vacuity in both directions across the LIVE registry:
//                  a clean tree renders nothing; a tree carrying each entry's
//                  legacy state renders exactly that entry's row.
//
// Report contract pinned here (shape precedent: `runMigrationCoverageProbe`):
//   runUpgradeStalenessProbe(projectRoot, registry?)
//     => {
//          rows:       string[];   // one byte-pinned row per applying entry
//          notes:      string[];   // the rendered NOTES block:
//                                  //   [...rows, UPGRADE_STALENESS_REMEDY]
//                                  //   when rows is non-empty, else []
//          violations: never[];    // ALWAYS empty — the probe never FAILs
//        }
//   plus `PROBE_ID` and the `UPGRADE_STALENESS_REMEDY` literal.
//
// The `registry` parameter defaults to the live MIGRATIONS list; tests inject
// synthetic registries to pin ordering, the `"; "` join, and the no-sort /
// no-truncate rules independently of any live detector's prose. Every call is
// `await`ed so the contract holds whether the implementation is sync or async.
//
// Fixture discipline (FR § Testing): mkdtempSync trees, per STE-391. Retired
// path literals are composed through `legacy_paths` helpers rather than
// spelled out, so this file needs no STE-384 carve-out of its own.

import { afterEach, describe, expect, test } from "bun:test";
import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";
import { MIGRATIONS, type MigrationEntry } from "../adapters/_shared/src/migrations/index";
import {
  LEGACY_HOOK_DIR_FRAGMENT,
  LEGACY_HOOK_SCRIPT_NAMES,
  LEGACY_ROOT_GITIGNORE_LINE,
  legacyLayoutMarker,
  legacyLedgerDir,
  legacyLocksDir,
} from "../adapters/_shared/src/migrations/legacy_paths";
import {
  PROBE_ID,
  UPGRADE_STALENESS_REMEDY,
  type UpgradeStalenessReport,
  runUpgradeStalenessProbe,
} from "../adapters/_shared/src/upgrade_staleness";

const repoRoot = join(import.meta.dir, "..", "..", "..");
const probeModulePath = join(
  repoRoot,
  "plugins",
  "dev-process-toolkit",
  "adapters",
  "_shared",
  "src",
  "upgrade_staleness.ts",
);
const gateCheckSkill = join(
  repoRoot,
  "plugins",
  "dev-process-toolkit",
  "skills",
  "gate-check",
  "SKILL.md",
);

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

const tmpRoots: string[] = [];

afterEach(() => {
  while (tmpRoots.length > 0) {
    const dir = tmpRoots.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

/** A CLAUDE.md that the toolkit owns, via the `/setup` generation marker. */
const MANAGED_BY_MARKER = "# Project\n\n<!-- generated by /dev-process-toolkit:setup -->\n\nProse.\n";
/** A CLAUDE.md that the toolkit owns, via the managed `## Task Tracking` section. */
const MANAGED_BY_TASK_TRACKING = "# Project\n\n## Task Tracking\n\nmode: none\n";
/** A CLAUDE.md that the toolkit owns, via the managed `## Docs` section. */
const MANAGED_BY_DOCS = "# Project\n\n## Docs\n\nuser_facing_mode: false\n";
/** A hand-written CLAUDE.md the toolkit does NOT own — no marker, no managed section. */
const UNMANAGED = "# My Project\n\n## Getting Started\n\nHand-written notes, no toolkit sections.\n";

/** An mkdtemp tree seeded from a relative-path → content map. */
function makeTree(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), "ste-394-staleness-"));
  tmpRoots.push(root);
  for (const [rel, body] of Object.entries(files)) {
    const full = join(root, ...rel.split("/"));
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, body, "utf-8");
  }
  return root;
}

/** Plant the pre-M104 tracked locks folder (m104-legacy-state, 1 evidence). */
function plantLegacyLocks(root: string): void {
  mkdirSync(legacyLocksDir(root), { recursive: true });
}

/** Plant ALL THREE m104-legacy-state signals, so `evidence` has length 3. */
function plantAllM104State(root: string): void {
  plantLegacyLocks(root);
  mkdirSync(legacyLedgerDir(root), { recursive: true });
  writeFileSync(
    join(root, ".gitignore"),
    `node_modules/\n${LEGACY_ROOT_GITIGNORE_LINE}\ndist/\n`,
    "utf-8",
  );
}

/** Plant the v1-era layout marker under specs/ (v1-orphans). */
function plantV1Orphan(root: string): void {
  const marker = legacyLayoutMarker(root);
  mkdirSync(dirname(marker), { recursive: true });
  writeFileSync(marker, "v1\n", "utf-8");
}

/** Plant a retired v2.21-era installer hook entry (stale-hook-entries). */
function plantStaleHookEntry(root: string): void {
  const script = `\${CLAUDE_PLUGIN_ROOT}/${LEGACY_HOOK_DIR_FRAGMENT}${LEGACY_HOOK_SCRIPT_NAMES[0]}`;
  const settings = {
    hooks: {
      PreToolUse: [{ matcher: "Bash", hooks: [{ type: "command", command: "bash", args: [script] }] }],
    },
  };
  const path = join(root, ".claude", "settings.json");
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(settings, null, 2)}\n`, "utf-8");
}

/**
 * Plant a retired glob-shaped allow rule (permission-shapes).
 *
 * The rule is COMPOSED, never spelled out: writing the literal shape would
 * plant the very pattern the toolkit's own hygiene probes scan for — the same
 * reasoning `legacy_paths.ts` gives for holding it as a regex.
 */
function plantLegacyPermissionShape(root: string): void {
  const globRule = `Bash(bun ${"*"})`;
  const path = join(root, ".claude", "settings.json");
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(
    path,
    `${JSON.stringify({ permissions: { allow: [globRule] } }, null, 2)}\n`,
    "utf-8",
  );
}

/** Plant a pre-pivot monolith: live FR sections + no specs/frs/ (monolith-split). */
function plantMonolith(root: string): void {
  const path = join(root, "specs", "requirements.md");
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(
    path,
    [
      "# Requirements",
      "",
      "### FR-1: First thing",
      "",
      "- AC-1.1: it works",
      "",
      "### FR-2: Second thing",
      "",
      "- AC-2.1: it also works",
      "",
    ].join("\n"),
    "utf-8",
  );
}

/** A synthetic entry whose detector returns a fixed verdict. */
function fixtureEntry(
  id: string,
  introducedIn: string,
  evidence: string[],
): MigrationEntry {
  return {
    id,
    introduced_in: introducedIn,
    title: `${id} (fixture)`,
    kind: "script",
    detect: () => ({ applies: evidence.length > 0, evidence }),
    apply: () => ({ changed: [], summary: "" }),
  };
}

/** Recursive `relpath → content|<dir>` snapshot, for the no-writes purity check. */
function snapshot(root: string): Record<string, string> {
  const out: Record<string, string> = {};
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir).sort()) {
      const abs = join(dir, name);
      const rel = relative(root, abs);
      if (statSync(abs).isDirectory()) {
        out[rel] = "<dir>";
        walk(abs);
      } else {
        out[rel] = readFileSync(abs, "utf-8");
      }
    }
  };
  walk(root);
  return out;
}

/** The live registry entry with this id — the detector prose belongs to it, not to us. */
function liveEntry(id: string): MigrationEntry {
  const entry = MIGRATIONS.find((e) => e.id === id);
  if (entry === undefined) throw new Error(`live registry has no entry "${id}"`);
  return entry;
}

// ---------------------------------------------------------------------------
// AC-STE-394.1 — probe identity + #69 registration
// ---------------------------------------------------------------------------

describe("AC-STE-394.1 — probe identity and #69 registration", () => {
  test("PROBE_ID is the literal string 'upgrade_staleness'", () => {
    expect(PROBE_ID).toBe("upgrade_staleness");
  });

  test("registered as the 69th numbered probe in gate-check SKILL.md", () => {
    const body = readFileSync(gateCheckSkill, "utf-8");
    expect(body).toMatch(/^69\.\s+\*\*`?upgrade_staleness`?\*\*/m);
  });

  test("#69 is registered directly after #68 migration_coverage", () => {
    const lines = readFileSync(gateCheckSkill, "utf-8").split("\n");
    const idx68 = lines.findIndex((l) => /^68\.\s+\*\*`?migration_coverage`?\*\*/.test(l));
    const idx69 = lines.findIndex((l) => /^69\.\s+\*\*`?upgrade_staleness`?\*\*/.test(l));
    expect(idx68).toBeGreaterThanOrEqual(0);
    expect(idx69).toBeGreaterThan(idx68);
  });
});

// ---------------------------------------------------------------------------
// AC-STE-394.1 / .4 — Step 0 applicability short-circuit
// ---------------------------------------------------------------------------

describe("AC-STE-394.1 — Step 0: no toolkit-managed CLAUDE.md section ⇒ short-circuit", () => {
  test("CLAUDE.md absent + legacy locks on disk ⇒ zero rows, no error", async () => {
    const root = makeTree({ "README.md": "# hi\n" });
    plantLegacyLocks(root);
    const r = await runUpgradeStalenessProbe(root);
    expect(r.rows).toEqual([]);
    expect(r.notes).toEqual([]);
    expect(r.violations).toEqual([]);
  });

  test("hand-written CLAUDE.md (no marker, no managed section) + legacy locks ⇒ zero rows", async () => {
    const root = makeTree({ "CLAUDE.md": UNMANAGED });
    plantLegacyLocks(root);
    const r = await runUpgradeStalenessProbe(root);
    expect(r.rows).toEqual([]);
    expect(r.notes).toEqual([]);
  });

  test("the short-circuit walks ZERO detectors — no entry's detect is ever called", async () => {
    const root = makeTree({ "CLAUDE.md": UNMANAGED });
    plantLegacyLocks(root);
    let calls = 0;
    const spy: MigrationEntry = {
      id: "spy-entry",
      introduced_in: "9.9.9",
      title: "spy",
      kind: "script",
      detect: () => {
        calls += 1;
        return { applies: true, evidence: ["spy fired"] };
      },
      apply: () => ({ changed: [], summary: "" }),
    };
    const r = await runUpgradeStalenessProbe(root, [spy]);
    expect(calls).toBe(0);
    expect(r.rows).toEqual([]);
  });
});

describe("AC-STE-394.1 — Step 0: a toolkit-managed section admits the walk", () => {
  const managedShapes: Array<[string, string]> = [
    ["the `/setup` generation marker", MANAGED_BY_MARKER],
    ["the managed `## Task Tracking` section", MANAGED_BY_TASK_TRACKING],
    ["the managed `## Docs` section", MANAGED_BY_DOCS],
  ];

  for (const [label, claudeMd] of managedShapes) {
    test(`${label} makes the tree in-scope, so the detector walk runs`, async () => {
      const root = makeTree({ "CLAUDE.md": claudeMd });
      plantLegacyLocks(root);
      const r = await runUpgradeStalenessProbe(root);
      expect(r.rows.length).toBe(1);
      expect(r.rows[0]!.startsWith("m104-legacy-state (2.46.0): ")).toBe(true);
    });
  }

  test("the walk visits every registry entry, in registry order", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const visited: string[] = [];
    const spyRegistry: MigrationEntry[] = ["gamma", "alpha", "beta"].map((id, i) => ({
      id,
      introduced_in: `1.${i}.0`,
      title: id,
      kind: "script",
      detect: () => {
        visited.push(id);
        return { applies: false, evidence: [] };
      },
      apply: () => ({ changed: [], summary: "" }),
    }));
    await runUpgradeStalenessProbe(root, spyRegistry);
    // Registry order, NOT alphabetical — the registry is version-ordered.
    expect(visited).toEqual(["gamma", "alpha", "beta"]);
  });

  test("rows render in registry order, one per applying entry, none for the rest", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const registry: MigrationEntry[] = [
      fixtureEntry("zulu-first", "1.0.0", ["z fired"]),
      fixtureEntry("quiet-entry", "1.1.0", []), // applies:false — renders nothing
      fixtureEntry("alpha-last", "1.2.0", ["a fired"]),
    ];
    const r = await runUpgradeStalenessProbe(root, registry);
    expect(r.rows).toEqual([
      "zulu-first (1.0.0): z fired",
      "alpha-last (1.2.0): a fired",
    ]);
  });

  test("the probe NEVER emits GATE FAILED — violations stay empty even with every entry firing", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    plantAllM104State(root);
    plantV1Orphan(root);
    plantStaleHookEntry(root);
    plantMonolith(root);
    const r = await runUpgradeStalenessProbe(root);
    expect(r.rows.length).toBeGreaterThan(0);
    expect(r.violations).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// AC-STE-394.2 — byte-pinned row shape
// ---------------------------------------------------------------------------

describe("AC-STE-394.2 — row shape `<id> (<introduced_in>): <evidence joined by \"; \">`", () => {
  test("single-evidence row is exactly `<id> (<version>): <evidence>`", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const r = await runUpgradeStalenessProbe(root, [
      fixtureEntry("solo-entry", "3.1.4", ["only one thing"]),
    ]);
    expect(r.rows).toEqual(["solo-entry (3.1.4): only one thing"]);
  });

  test("multi-evidence joins with EXACTLY `\"; \"` — no trailing separator, no bullets", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const r = await runUpgradeStalenessProbe(root, [
      fixtureEntry("triple", "2.0.0", ["one", "two", "three"]),
    ]);
    expect(r.rows).toEqual(["triple (2.0.0): one; two; three"]);
  });

  test("evidence order is the detector's returned order — NEVER re-sorted", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    // Deliberately anti-alphabetical: a sorting implementation cannot pass.
    const r = await runUpgradeStalenessProbe(root, [
      fixtureEntry("unsorted", "1.0.0", ["zebra", "alpha", "middle"]),
    ]);
    expect(r.rows).toEqual(["unsorted (1.0.0): zebra; alpha; middle"]);
  });

  test("evidence is NEVER truncated — every item survives, however many or long", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const evidence = Array.from({ length: 8 }, (_, i) => `${"e".repeat(120)}-${i}`);
    const r = await runUpgradeStalenessProbe(root, [fixtureEntry("verbose", "1.0.0", evidence)]);
    expect(r.rows).toEqual([`verbose (1.0.0): ${evidence.join("; ")}`]);
    for (const item of evidence) expect(r.rows[0]!).toContain(item);
    expect(r.rows[0]!).not.toContain("…");
    expect(r.rows[0]!).not.toContain("...");
  });

  test("the LIVE m104-legacy-state row pins the shape against real detector prose", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    plantAllM104State(root);
    const r = await runUpgradeStalenessProbe(root);
    const entry = liveEntry("m104-legacy-state");
    const detected = entry.detect(root);
    // Three signals planted ⇒ three evidence strings ⇒ two `"; "` separators.
    expect(detected.evidence.length).toBe(3);
    const row = r.rows.find((l) => l.startsWith("m104-legacy-state "));
    expect(row).toBeDefined();
    expect(row).toBe(
      `${entry.id} (${entry.introduced_in}): ${detected.evidence.join("; ")}`,
    );
    expect(row!.split("; ").length).toBe(3);
  });
});

// ---------------------------------------------------------------------------
// AC-STE-394.5 — the byte-pinned remedy literal
// ---------------------------------------------------------------------------

describe("AC-STE-394.5 — remedy literal fires exactly once, and only with rows", () => {
  test("the exported literal is byte-exact", () => {
    expect(UPGRADE_STALENESS_REMEDY).toBe(
      "Remedy: run /dev-process-toolkit:upgrade to apply these migrations (Claude can invoke it; it is not on the slash menu).",
    );
  });

  test("with >= 1 row the NOTES block CLOSES with the remedy, exactly once", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const r = await runUpgradeStalenessProbe(root, [
      fixtureEntry("a-entry", "1.0.0", ["a"]),
      fixtureEntry("b-entry", "1.1.0", ["b"]),
    ]);
    expect(r.rows.length).toBe(2);
    expect(r.notes).toEqual([...r.rows, UPGRADE_STALENESS_REMEDY]);
    expect(r.notes[r.notes.length - 1]).toBe(UPGRADE_STALENESS_REMEDY);
    const occurrences = r.notes.filter((n) => n === UPGRADE_STALENESS_REMEDY).length;
    expect(occurrences).toBe(1);
    // Once per RUN, not once per row.
    const inline = r.notes.join("\n").split(UPGRADE_STALENESS_REMEDY).length - 1;
    expect(inline).toBe(1);
  });

  test("with ZERO rows the remedy is never emitted", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const r = await runUpgradeStalenessProbe(root, [fixtureEntry("quiet", "1.0.0", [])]);
    expect(r.rows).toEqual([]);
    expect(r.notes).toEqual([]);
    expect(r.notes.join("\n")).not.toContain("dev-process-toolkit:upgrade");
  });

  test("the short-circuit path emits no remedy either", async () => {
    const root = makeTree({ "CLAUDE.md": UNMANAGED });
    plantAllM104State(root);
    const r = await runUpgradeStalenessProbe(root);
    expect(r.notes.join("\n")).not.toContain(UPGRADE_STALENESS_REMEDY);
  });
});

// ---------------------------------------------------------------------------
// AC-STE-394.3 — purity
// ---------------------------------------------------------------------------

describe("AC-STE-394.3 — probe purity", () => {
  test("two runs over the same tree return identical verdicts", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    plantAllM104State(root);
    plantV1Orphan(root);
    const a = await runUpgradeStalenessProbe(root);
    const b = await runUpgradeStalenessProbe(root);
    expect(b.rows).toEqual(a.rows);
    expect(b.notes).toEqual(a.notes);
    expect(b.violations).toEqual(a.violations);
  });

  test("the probe writes nothing — the tree is byte-identical afterwards", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    plantAllM104State(root);
    plantV1Orphan(root);
    const before = snapshot(root);
    await runUpgradeStalenessProbe(root);
    expect(snapshot(root)).toEqual(before);
  });

  test("the module source spawns no process and opens no socket", () => {
    const src = readFileSync(probeModulePath, "utf-8");
    expect(src).not.toMatch(/child_process/);
    expect(src).not.toMatch(/\bexecSync\b|\bspawnSync\b|\bBun\.spawn\b|\bBun\.\$/);
    expect(src).not.toMatch(/\bfetch\s*\(/);
    expect(src).not.toMatch(/node:https?|\bWebSocket\b/);
  });

  test("registry defaults to the live MIGRATIONS list when omitted", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    plantLegacyLocks(root);
    const r = await runUpgradeStalenessProbe(root);
    expect(r.rows.length).toBe(1);
    expect(r.rows[0]!.startsWith("m104-legacy-state (2.46.0): ")).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// AC-STE-394.4 / .9 — non-vacuity in both directions over the LIVE registry
// ---------------------------------------------------------------------------

describe("AC-STE-394.4 — vacuous in both directions", () => {
  test("a clean managed tree renders zero rows and zero notes", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING, "README.md": "# clean\n" });
    const r = await runUpgradeStalenessProbe(root);
    expect(r.rows).toEqual([]);
    expect(r.notes).toEqual([]);
    expect(r.violations).toEqual([]);
  });

  test("a bare root (no CLAUDE.md, nothing else) is clean, not an error", async () => {
    const root = makeTree({});
    const r = await runUpgradeStalenessProbe(root);
    expect(r.rows).toEqual([]);
    expect(r.notes).toEqual([]);
  });

  test("consumer-safety case: legacy locks + NO managed CLAUDE.md section ⇒ zero rows", async () => {
    // The case that distinguishes the Step 0 short-circuit from a plain no-hit:
    // the detector WOULD fire on this tree, and the short-circuit is why it does not.
    const root = makeTree({ "CLAUDE.md": UNMANAGED });
    plantAllM104State(root);
    expect(liveEntry("m104-legacy-state").detect(root).applies).toBe(true);
    const r = await runUpgradeStalenessProbe(root);
    expect(r.rows).toEqual([]);
    expect(r.notes).toEqual([]);
    expect(r.violations).toEqual([]);
  });
});

describe("AC-STE-394.9 — each live legacy state renders exactly its own row", () => {
  const cases: Array<[string, (root: string) => void]> = [
    ["m104-legacy-state", plantLegacyLocks],
    ["v1-orphans", plantV1Orphan],
    ["stale-hook-entries", plantStaleHookEntry],
    ["permission-shapes", plantLegacyPermissionShape],
    ["monolith-split", plantMonolith],
  ];

  // Completeness guard. Without it the table above is a hand-maintained list
  // that a SIXTH registry entry would silently slip past — leaving "each legacy
  // state" coincidental rather than enforced, which is the same silent-disable
  // class AC-STE-394.8 exists to repair. Adding a registry entry now reds here
  // until its fixture lands.
  test("the case table covers EVERY live registry entry — none can be added uncovered", () => {
    expect(cases.map(([id]) => id).sort()).toEqual(MIGRATIONS.map((e) => e.id).sort());
  });

  for (const [id, plant] of cases) {
    test(`a tree carrying only ${id}'s legacy state renders exactly one row, for ${id}`, async () => {
      const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
      plant(root);
      const r = await runUpgradeStalenessProbe(root);
      const entry = liveEntry(id);
      expect(r.rows.length).toBe(1);
      expect(r.rows[0]!.startsWith(`${entry.id} (${entry.introduced_in}): `)).toBe(true);
      expect(r.rows[0]).toBe(
        `${entry.id} (${entry.introduced_in}): ${entry.detect(root).evidence.join("; ")}`,
      );
      expect(r.notes[r.notes.length - 1]).toBe(UPGRADE_STALENESS_REMEDY);
    });
  }

  test("a tree carrying several legacy states renders one row per entry, in registry order", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    plantMonolith(root); // monolith-split — 1.16.0, first in registry order
    plantV1Orphan(root); // v1-orphans     — 1.20.0
    plantLegacyLocks(root); // m104-legacy-state — 2.46.0, last
    const r = await runUpgradeStalenessProbe(root);
    const ids = r.rows.map((row) => row.slice(0, row.indexOf(" (")));
    expect(ids).toEqual(["monolith-split", "v1-orphans", "m104-legacy-state"]);
    expect(r.notes).toEqual([...r.rows, UPGRADE_STALENESS_REMEDY]);
  });
});

// ---------------------------------------------------------------------------
// Dogfood — the probe runs on the REAL toolkit tree without throwing.
//
// The toolkit's own repo IS toolkit-managed (its CLAUDE.md carries the managed
// `## Task Tracking` section), so this exercises the full walk against real
// detectors. Rows are NOT asserted empty: a transient legacy artifact on a
// working tree is exactly the advisory this probe exists to surface, and a
// zero-row assert would red the gate on the thing it is meant to report.
// ---------------------------------------------------------------------------

describe("dogfood — the probe walks the real toolkit tree", () => {
  test("running against the repo root never produces a violation", async () => {
    const r = await runUpgradeStalenessProbe(repoRoot);
    expect(r.violations).toEqual([]);
    expect(Array.isArray(r.rows)).toBe(true);
  });

  test("every rendered row on the real tree carries the byte-pinned shape", async () => {
    const r = await runUpgradeStalenessProbe(repoRoot);
    for (const row of r.rows) {
      expect(row).toMatch(/^[a-z0-9-]+ \(\d+\.\d+\.\d+\): .+/);
    }
    if (r.rows.length > 0) {
      expect(r.notes[r.notes.length - 1]).toBe(UPGRADE_STALENESS_REMEDY);
    } else {
      expect(r.notes).toEqual([]);
    }
  });
});

// ---------------------------------------------------------------------------
// HARDENING — a throwing detector must not crash the probe
//
// Found and reproduced during /implement Phase 3 Stage C (error-path audit).
// `upgrade_staleness.ts` calls `entry.detect(projectRoot)` with no guard, so a
// detector that throws propagates out of `runUpgradeStalenessProbe` and takes
// the whole gate run down with it. That is strictly WORSE than the GATE FAILED
// AC-STE-394.1 forbids: a FAILED verdict is a verdict, a thrown probe is a
// crashed gate.
//
// The failure is reachable against the LIVE registry, not only synthetically:
// `m104-legacy-state`'s detector reads the consumer's ROOT `.gitignore` via
// `readLines` → `readFileSync`, which throws EACCES on an unreadable file.
//
// Contract these tests pin:
//   1. a throwing detector never rejects the probe — it resolves;
//   2. `violations` stays empty (AC-STE-394.1's never-FAIL contract survives
//      the error path — degrade, do not escalate);
//   3. the failure is NOT swallowed silently — the erroring entry surfaces a
//      row, and that row stays inside the AC-STE-394.2 byte-pinned shape
//      `<entry-id> (<introduced_in>): <evidence>`, with the thrown message
//      carried as the evidence text;
//   4. one throwing entry does not suppress the entries around it, in either
//      registry position;
//   5. the AC-STE-394.5 remedy still fires exactly once when rows exist,
//      error rows included.
// ---------------------------------------------------------------------------

/** Root bypasses file permission bits, so chmod-based cases cannot go RED there. */
const isRoot = process.getuid?.() === 0;

/** A synthetic entry whose detector throws instead of returning a verdict. */
function throwingEntry(id: string, introducedIn: string, message: string): MigrationEntry {
  return {
    id,
    introduced_in: introducedIn,
    title: `${id} (throwing fixture)`,
    kind: "script",
    detect: () => {
      throw new Error(message);
    },
    apply: () => ({ changed: [], summary: "" }),
  };
}

/**
 * Run the probe and report resolve-vs-reject as DATA rather than letting a
 * rejection blow up the test body — so a regression reads as "PROBE THREW"
 * instead of an opaque unhandled error.
 */
async function runOrCapture(
  root: string,
  registry?: readonly MigrationEntry[],
): Promise<{ report: UpgradeStalenessReport | null; error: unknown }> {
  try {
    return { report: await runUpgradeStalenessProbe(root, registry), error: null };
  } catch (error) {
    return { report: null, error };
  }
}

describe("HARDENING — a throwing detector degrades to a row, never to a crash", () => {
  const BOOM = "detector exploded";

  test("the probe RESOLVES — a throwing detector does not reject the run", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const { report, error } = await runOrCapture(root, [throwingEntry("boom-entry", "1.0.0", BOOM)]);
    expect(error).toBeNull();
    expect(report).not.toBeNull();
    expect(Array.isArray(report!.rows)).toBe(true);
  });

  test("the never-FAIL contract holds under detector error — violations stay empty", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const { report, error } = await runOrCapture(root, [throwingEntry("boom-entry", "1.0.0", BOOM)]);
    expect(error).toBeNull();
    expect(report!.violations).toEqual([]);
  });

  test("the error is NOT silent — the erroring entry surfaces exactly one row", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const { report, error } = await runOrCapture(root, [throwingEntry("boom-entry", "1.0.0", BOOM)]);
    expect(error).toBeNull();
    expect(report!.rows.length).toBe(1);
  });

  test("the error row keeps the AC-STE-394.2 byte-pinned shape and carries the message", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const { report, error } = await runOrCapture(root, [throwingEntry("boom-entry", "4.5.6", BOOM)]);
    expect(error).toBeNull();
    const row = report!.rows[0]!;
    // Same shape the dogfood block pins for healthy rows: `<id> (<version>): <evidence>`.
    expect(row).toMatch(/^[a-z0-9-]+ \(\d+\.\d+\.\d+\): .+/);
    expect(row.startsWith("boom-entry (4.5.6): ")).toBe(true);
    // The evidence text must carry the thrown message — otherwise the row says
    // "something is wrong here" with no way to tell what.
    expect(row).toContain(BOOM);
    // ...and must read as an error, not as ordinary legacy-state evidence.
    expect(row).toMatch(/error/i);
    // The shape is one line: a raw multi-line dump would break the NOTES block.
    expect(row).not.toContain("\n");
  });

  test("a thrown non-Error value still renders a row instead of crashing", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const stringThrower: MigrationEntry = {
      id: "string-thrower",
      introduced_in: "2.0.0",
      title: "throws a bare string",
      kind: "script",
      detect: () => {
        throw "bare string failure";
      },
      apply: () => ({ changed: [], summary: "" }),
    };
    const { report, error } = await runOrCapture(root, [stringThrower]);
    expect(error).toBeNull();
    expect(report!.rows.length).toBe(1);
    expect(report!.rows[0]!.startsWith("string-thrower (2.0.0): ")).toBe(true);
    expect(report!.rows[0]!).toContain("bare string failure");
    expect(report!.violations).toEqual([]);
  });

  test("a throwing FIRST entry does not suppress the applying entry after it", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const { report, error } = await runOrCapture(root, [
      throwingEntry("boom-entry", "1.0.0", BOOM),
      fixtureEntry("healthy-entry", "1.1.0", ["legacy thing present"]),
    ]);
    expect(error).toBeNull();
    expect(report!.rows.length).toBe(2);
    // The healthy row renders EXACTLY as it would with no throwing sibling.
    expect(report!.rows[1]).toBe("healthy-entry (1.1.0): legacy thing present");
    expect(report!.rows[0]!.startsWith("boom-entry (1.0.0): ")).toBe(true);
  });

  test("a throwing LAST entry renders after the applying one — both rows, registry order", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const { report, error } = await runOrCapture(root, [
      fixtureEntry("healthy-entry", "1.1.0", ["legacy thing present"]),
      throwingEntry("boom-entry", "1.2.0", BOOM),
    ]);
    expect(error).toBeNull();
    expect(report!.rows.length).toBe(2);
    expect(report!.rows[0]).toBe("healthy-entry (1.1.0): legacy thing present");
    expect(report!.rows[1]!.startsWith("boom-entry (1.2.0): ")).toBe(true);
    expect(report!.rows[1]!).toContain(BOOM);
  });

  test("a non-applying entry between two throwers still renders nothing", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const { report, error } = await runOrCapture(root, [
      throwingEntry("boom-one", "1.0.0", "first boom"),
      fixtureEntry("quiet-entry", "1.1.0", []),
      throwingEntry("boom-two", "1.2.0", "second boom"),
    ]);
    expect(error).toBeNull();
    const ids = report!.rows.map((row) => row.slice(0, row.indexOf(" (")));
    expect(ids).toEqual(["boom-one", "boom-two"]);
  });

  test("the remedy literal fires exactly once when the only rows are error rows", async () => {
    const root = makeTree({ "CLAUDE.md": MANAGED_BY_TASK_TRACKING });
    const { report, error } = await runOrCapture(root, [
      throwingEntry("boom-one", "1.0.0", "first boom"),
      throwingEntry("boom-two", "1.1.0", "second boom"),
    ]);
    expect(error).toBeNull();
    expect(report!.rows.length).toBe(2);
    expect(report!.notes).toEqual([...report!.rows, UPGRADE_STALENESS_REMEDY]);
    const occurrences = report!.notes.filter((n) => n === UPGRADE_STALENESS_REMEDY).length;
    expect(occurrences).toBe(1);
  });

  test("the Step 0 short-circuit still runs BEFORE any detector can throw", async () => {
    // An unmanaged tree must stay clean even when every registry entry would
    // explode — the short-circuit is what keeps the probe silent on trees the
    // toolkit does not own, and an error path must not smuggle rows past it.
    const root = makeTree({ "CLAUDE.md": UNMANAGED });
    const { report, error } = await runOrCapture(root, [throwingEntry("boom-entry", "1.0.0", BOOM)]);
    expect(error).toBeNull();
    expect(report!.rows).toEqual([]);
    expect(report!.notes).toEqual([]);
    expect(report!.violations).toEqual([]);
  });
});

describe("HARDENING — the LIVE registry survives an unreadable consumer file", () => {
  // Reproduces the real-world reachable case: `m104-legacy-state`'s detector
  // reads the ROOT `.gitignore`, so a tree whose `.gitignore` is chmod 000
  // throws EACCES out of the live detector walk. Skipped as root, which
  // bypasses permission bits (same convention as
  // `tests/m108-ste-392-monolith-flow.test.ts`).

  /** Managed tree whose root `.gitignore` exists but cannot be read. */
  function makeUnreadableGitignoreTree(): { root: string; gitignore: string } {
    const root = makeTree({
      "CLAUDE.md": MANAGED_BY_TASK_TRACKING,
      ".gitignore": "node_modules/\ndist/\n",
    });
    const gitignore = join(root, ".gitignore");
    chmodSync(gitignore, 0o000);
    return { root, gitignore };
  }

  test.skipIf(isRoot)("the live probe RESOLVES instead of throwing EACCES", async () => {
    const { root, gitignore } = makeUnreadableGitignoreTree();
    try {
      // Precondition: the live detector really does throw on this tree, so this
      // case is non-vacuous — it is the crash, not a hypothetical.
      expect(() => liveEntry("m104-legacy-state").detect(root)).toThrow();
      const { report, error } = await runOrCapture(root);
      expect(error).toBeNull();
      expect(report!.violations).toEqual([]);
    } finally {
      chmodSync(gitignore, 0o644);
    }
  });

  test.skipIf(isRoot)("the EACCES surfaces as a byte-pinned m104-legacy-state row", async () => {
    const { root, gitignore } = makeUnreadableGitignoreTree();
    try {
      const { report, error } = await runOrCapture(root);
      expect(error).toBeNull();
      const entry = liveEntry("m104-legacy-state");
      const row = report!.rows.find((l) => l.startsWith(`${entry.id} (${entry.introduced_in}): `));
      expect(row).toBeDefined();
      expect(row!).toMatch(/^[a-z0-9-]+ \(\d+\.\d+\.\d+\): .+/);
      // The operator must be able to see WHICH file the probe could not read.
      expect(row!).toMatch(/EACCES|permission denied/i);
      expect(row!).toContain(".gitignore");
      // The advisory still closes with the remedy, exactly once.
      expect(report!.notes).toEqual([...report!.rows, UPGRADE_STALENESS_REMEDY]);
    } finally {
      chmodSync(gitignore, 0o644);
    }
  });

  test.skipIf(isRoot)("healthy live entries still report normally alongside the erroring one", async () => {
    const { root, gitignore } = makeUnreadableGitignoreTree();
    try {
      plantV1Orphan(root); // v1-orphans applies and must survive m104's throw
      const { report, error } = await runOrCapture(root);
      expect(error).toBeNull();
      const v1 = liveEntry("v1-orphans");
      const row = report!.rows.find((l) => l.startsWith(`${v1.id} (${v1.introduced_in}): `));
      expect(row).toBeDefined();
      expect(row).toBe(`${v1.id} (${v1.introduced_in}): ${v1.detect(root).evidence.join("; ")}`);
      expect(report!.violations).toEqual([]);
    } finally {
      chmodSync(gitignore, 0o644);
    }
  });
});
