import { describe, expect, test } from "bun:test";
import { execSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runSetupBootstrapCommittedProbe } from "../adapters/_shared/src/setup_bootstrap_committed";

// STE-109 AC-STE-109.7 / AC-STE-109.8 — `setup-bootstrap-committed` probe.
//
// Trigger: CLAUDE.md is toolkit-managed (carries the
// `<!-- generated by /dev-process-toolkit:setup -->` marker) AND the file
// is currently in the working tree. It MUST be committed (no `??` or
// modification status in `git status --porcelain`).
//
// Three fixtures:
//   (a) toolkit-managed + committed → pass
//   (b) toolkit-managed + untracked → fail
//   (c) toolkit-managed + modified  → fail
//   (d) hand-written CLAUDE.md (no marker) → vacuous pass
//   (e) no git repo → vacuous pass

const pluginRoot = join(import.meta.dir, "..");
const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

function git(cwd: string, ...args: string[]): string {
  return execSync(`git ${args.join(" ")}`, { cwd, encoding: "utf-8" }).trim();
}

function makeRepo(opts: {
  initGit: boolean;
  claudeMdContent?: string;
  commit?: boolean;
}): { root: string; cleanup: () => void } {
  const root = mkdtempSync(join(tmpdir(), "bootstrap-committed-"));
  if (opts.initGit) {
    git(root, "init", "-q");
    git(root, "config", "user.email", "test@example.com");
    git(root, "config", "user.name", "Test");
    // Initial empty commit so the working tree has a HEAD.
    git(root, "commit", "--allow-empty", "-m", "init", "-q");
  }
  if (opts.claudeMdContent !== undefined) {
    writeFileSync(join(root, "CLAUDE.md"), opts.claudeMdContent);
    if (opts.commit) {
      git(root, "add", "CLAUDE.md");
      git(root, "commit", "-m", "bootstrap", "-q");
    }
  }
  return { root, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

describe("AC-STE-109.7(a) toolkit-managed + committed → pass", () => {
  test("committed CLAUDE.md → no violations", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commit: true,
    });
    try {
      const report = await runSetupBootstrapCommittedProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7(b) toolkit-managed + untracked → fail", () => {
  test("untracked CLAUDE.md flagged", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commit: false,
    });
    try {
      const report = await runSetupBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      const v = report.violations[0]!;
      expect(v.note).toMatch(/CLAUDE\.md/);
      expect(v.note).toMatch(/untracked|uncommitted|modified/i);
      expect(v.message).toMatch(/Remedy:/);
      expect(v.message).toMatch(/Context:/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7(c) toolkit-managed + modified → fail", () => {
  test("modified-but-tracked CLAUDE.md flagged", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commit: true,
    });
    try {
      // Modify in place, do not stage/commit.
      writeFileSync(
        join(ctx.root, "CLAUDE.md"),
        `${TOOLKIT_MARKER}\n\n# Project (edited)\n`,
      );
      const report = await runSetupBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7(d) hand-written CLAUDE.md (no marker) → vacuous pass", () => {
  test("untracked but no marker → no violations", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `# Project\n\nA hand-written file.\n`,
      commit: false,
    });
    try {
      const report = await runSetupBootstrapCommittedProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7(e) non-repo → vacuous pass", () => {
  test("no .git → no violations", async () => {
    const ctx = makeRepo({
      initGit: false,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
    });
    try {
      const report = await runSetupBootstrapCommittedProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });

  test("no CLAUDE.md at all → no violations", async () => {
    const ctx = makeRepo({ initGit: true });
    try {
      const report = await runSetupBootstrapCommittedProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7 — gate-check SKILL.md prose declares the probe", () => {
  const gateCheckSkill = readFileSync(
    join(pluginRoot, "skills", "gate-check", "SKILL.md"),
    "utf-8",
  );
  test("SKILL.md references probe `setup-bootstrap-committed`", () => {
    expect(gateCheckSkill).toMatch(/setup-bootstrap-committed/);
  });
});
