import { describe, expect, test } from "bun:test";
import { execSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runToolkitBootstrapCommittedProbe } from "../adapters/_shared/src/toolkit_bootstrap_committed";

// STE-109 AC-STE-109.7 / AC-STE-109.8 + STE-179 AC-STE-179.3 —
// `toolkit-bootstrap-committed` probe (renamed from `setup-bootstrap-committed`,
// scan-set widened from CLAUDE.md only to CLAUDE.md + .claude/settings.json
// + .mcp.json + every active file under specs/).
//
// Trigger: CLAUDE.md is toolkit-managed (carries the
// `<!-- generated by /dev-process-toolkit:setup -->` marker) AND the file is
// currently in the working tree. Every toolkit-managed file MUST be
// committed (no `??` / modification status in `git status --porcelain`).
//
// Original 5 fixtures (STE-109):
//   (a) toolkit-managed CLAUDE.md + committed → pass
//   (b) toolkit-managed CLAUDE.md + untracked → fail
//   (c) toolkit-managed CLAUDE.md + modified  → fail
//   (d) hand-written CLAUDE.md (no marker) → vacuous pass
//   (e) no git repo → vacuous pass
//
// New widened-scope fixtures (STE-179):
//   (f) specs/frs/<id>.md untracked → fail
//   (g) specs/technical-spec.md untracked → fail
//   (h) specs/testing-spec.md untracked → fail
//   (i) specs/plan/M<N>.md untracked → fail

const pluginRoot = join(import.meta.dir, "..");
const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

function git(cwd: string, ...args: string[]): string {
  return execSync(`git ${args.join(" ")}`, { cwd, encoding: "utf-8" }).trim();
}

interface RepoOptions {
  initGit: boolean;
  claudeMdContent?: string;
  commitClaudeMd?: boolean;
  specsFiles?: { path: string; content: string; commit?: boolean }[];
}

function makeRepo(opts: RepoOptions): { root: string; cleanup: () => void } {
  const root = mkdtempSync(join(tmpdir(), "toolkit-bootstrap-"));
  if (opts.initGit) {
    git(root, "init", "-q");
    git(root, "config", "user.email", "test@example.com");
    git(root, "config", "user.name", "Test");
    git(root, "commit", "--allow-empty", "-m", "init", "-q");
  }
  if (opts.claudeMdContent !== undefined) {
    writeFileSync(join(root, "CLAUDE.md"), opts.claudeMdContent);
    if (opts.commitClaudeMd) {
      git(root, "add", "CLAUDE.md");
      git(root, "commit", "-m", "bootstrap", "-q");
    }
  }
  if (opts.specsFiles !== undefined) {
    for (const f of opts.specsFiles) {
      const full = join(root, f.path);
      const dir = full.slice(0, full.lastIndexOf("/"));
      mkdirSync(dir, { recursive: true });
      writeFileSync(full, f.content);
      if (f.commit) {
        git(root, "add", f.path);
        git(root, "commit", "-m", `add ${f.path}`, "-q");
      }
    }
  }
  return { root, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

describe("AC-STE-109.7(a) toolkit-managed CLAUDE.md + committed → pass", () => {
  test("committed CLAUDE.md, no specs → no violations", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: true,
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7(b) toolkit-managed CLAUDE.md + untracked → fail", () => {
  test("untracked CLAUDE.md flagged", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: false,
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      const v = report.violations[0]!;
      expect(v.note).toMatch(/CLAUDE\.md/);
      expect(v.message).toMatch(/Remedy:/);
      expect(v.message).toMatch(/Context:/);
      expect(v.message).toMatch(/probe=toolkit_bootstrap_committed/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7(c) toolkit-managed CLAUDE.md + modified → fail", () => {
  test("modified-but-tracked CLAUDE.md flagged", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: true,
    });
    try {
      writeFileSync(
        join(ctx.root, "CLAUDE.md"),
        `${TOOLKIT_MARKER}\n\n# Project (edited)\n`,
      );
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7(d) hand-written CLAUDE.md (no marker) → vacuous pass", () => {
  test("untracked but no marker → no violations (probe gated on marker)", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `# Project\n\nA hand-written file.\n`,
      commitClaudeMd: false,
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-109.7(e) non-repo → vacuous pass", () => {
  test("no .git → no violations", async () => {
    const ctx = makeRepo({
      initGit: false,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });

  test("no CLAUDE.md at all → no violations", async () => {
    const ctx = makeRepo({ initGit: true });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-179.3(f) specs/frs/<id>.md untracked → fail", () => {
  test("toolkit-managed CLAUDE.md committed + uncommitted FR file → violation on FR", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: true,
      specsFiles: [
        { path: "specs/frs/STE-1.md", content: "---\ntitle: foo\n---\n# foo\n", commit: false },
      ],
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      const v = report.violations[0]!;
      expect(v.note).toMatch(/specs\/frs\/STE-1\.md/);
      expect(v.message).toMatch(/spec-write/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-179.3(g) specs/technical-spec.md untracked → fail", () => {
  test("uncommitted technical spec → violation", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: true,
      specsFiles: [
        { path: "specs/technical-spec.md", content: "# Tech\n", commit: false },
      ],
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      expect(report.violations[0]!.note).toMatch(/specs\/technical-spec\.md/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-179.3(h) specs/testing-spec.md untracked → fail", () => {
  test("uncommitted testing spec → violation", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: true,
      specsFiles: [
        { path: "specs/testing-spec.md", content: "# Testing\n", commit: false },
      ],
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      expect(report.violations[0]!.note).toMatch(/specs\/testing-spec\.md/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-179.3(i) specs/plan/M<N>.md untracked → fail", () => {
  test("uncommitted plan file → violation", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: true,
      specsFiles: [
        { path: "specs/plan/M1.md", content: "# M1\n", commit: false },
      ],
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      expect(report.violations[0]!.note).toMatch(/specs\/plan\/M1\.md/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-179.3 — multiple uncommitted toolkit files → violations for each", () => {
  test("FR + plan + testing spec untracked → three violations, one per file", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: true,
      specsFiles: [
        { path: "specs/frs/STE-2.md", content: "---\ntitle: bar\n---\n# bar\n", commit: false },
        { path: "specs/plan/M2.md", content: "# M2\n", commit: false },
        { path: "specs/testing-spec.md", content: "# Testing\n", commit: false },
      ],
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(3);
      const noteStr = report.violations.map((v) => v.note).join("\n");
      expect(noteStr).toMatch(/specs\/frs\/STE-2\.md/);
      expect(noteStr).toMatch(/specs\/plan\/M2\.md/);
      expect(noteStr).toMatch(/specs\/testing-spec\.md/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-179.3 — committed specs files alongside untracked CLAUDE.md → only CLAUDE.md flagged", () => {
  test("committed specs/* + untracked CLAUDE.md → 1 violation on CLAUDE.md", async () => {
    const ctx = makeRepo({
      initGit: true,
      claudeMdContent: `${TOOLKIT_MARKER}\n\n# Project\n`,
      commitClaudeMd: false,
      specsFiles: [
        { path: "specs/technical-spec.md", content: "# Tech\n", commit: true },
      ],
    });
    try {
      const report = await runToolkitBootstrapCommittedProbe(ctx.root);
      expect(report.violations.length).toBe(1);
      expect(report.violations[0]!.note).toMatch(/CLAUDE\.md/);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-179.4 — gate-check SKILL.md prose declares the renamed probe", () => {
  const gateCheckSkill = readFileSync(
    join(pluginRoot, "skills", "gate-check", "SKILL.md"),
    "utf-8",
  );
  test("SKILL.md references the new probe name `toolkit-bootstrap-committed`", () => {
    expect(gateCheckSkill).toMatch(/toolkit-bootstrap-committed/);
  });

  test("SKILL.md no longer references the old probe name `setup-bootstrap-committed`", () => {
    // Hard rename per AC-STE-179.3 — no aliasing, no users yet.
    expect(gateCheckSkill).not.toMatch(/setup-bootstrap-committed/);
  });
});

describe("AC-STE-139.5 — toolkit-bootstrap-committed runs clean on this repo's baseline", () => {
  test("runToolkitBootstrapCommittedProbe(repoRoot) returns zero violations on the toolkit repo", async () => {
    // The toolkit's own CLAUDE.md is hand-written (no marker) — probe
    // returns vacuous.
    const repoRoot = join(pluginRoot, "..", "..");
    const report = await runToolkitBootstrapCommittedProbe(repoRoot);
    expect(report.violations).toEqual([]);
  });
});
