import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Doc-hygiene regression guard for STE-64 AC-STE-64.12.
//
// `/gate-check` probe #10 asserts at runtime that `templates/CLAUDE.md.template`
// documents the `branch_template:` Schema L key. If the key silently drops out
// of the template, downstream projects generated by `/setup` would have branch
// automation silently disabled (the AC-STE-64.1 "absent ⇒ disabled" backward-
// compat rule reads correctly in prose but the user never learns the key
// exists). This test is the backing regression canary — equivalent to the
// runtime grep the probe runs, but exercised inside the test suite.

const pluginRoot = join(import.meta.dir, "..");
const templatePath = join(pluginRoot, "templates", "CLAUDE.md.template");

describe("STE-64 AC-STE-64.12 — CLAUDE.md.template documents branch_template:", () => {
  test("template file contains the literal substring `branch_template:`", () => {
    const body = readFileSync(templatePath, "utf-8");
    expect(body).toContain("branch_template:");
  });

  test("template's branch_template: documentation names both mode defaults (AC-STE-64.1)", () => {
    // Traces to AC-STE-64.1's default-for-mode contract: `{type}/m{N}-{slug}`
    // in `mode: none`, `{type}/{ticket-id}-{slug}` in tracker mode. The
    // `/gate-check` probe #10 (AC-STE-64.12) catches a zero-match grep, but
    // a template that listed only one default would still satisfy the probe
    // while silently forcing every downstream project into one mode. This
    // test enforces the stronger invariant — both defaults must remain
    // discoverable in the template so `/setup` step 7c's prompt can resolve
    // either one.
    const body = readFileSync(templatePath, "utf-8");
    expect(body).toContain("{type}/m{N}-{slug}");
    expect(body).toContain("{type}/{ticket-id}-{slug}");
  });
});
