// STE-153 AC-STE-153.9 — end-to-end fixture for /setup's unconditional
// audit-section synthesis.
//
// Generates a toolkit-managed CLAUDE.md as if /setup ran in autonomous mode
// with every Schema L answer pre-baked, builds the corresponding
// resolvedSchemaLValues table (4 entries), calls synthesizeAuditSection,
// then runs runSetupAuditSectionPresenceProbe against the resulting file.
//
// Three scenarios per the FR's behaviour matrix:
//   (a) all-explicit (every reason: "user-supplied")
//   (b) all-default (every reason: "default applied", existing v1.41.0 path)
//   (c) mixed (branchTemplate user-supplied + docs.* default applied)
//
// The probe must return zero violations in every case — the audit section
// is now a deterministic byproduct of every well-formed /setup run, not
// only of default-applied outcomes.

import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  synthesizeAuditSection,
  type ResolvedSchemaLValues,
} from "../adapters/_shared/src/setup/synthesize_audit";
import { runSetupAuditSectionPresenceProbe } from "../adapters/_shared/src/setup_audit_section_presence";

const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

function makeProject(claudeMdContent: string): { root: string; cleanup: () => void } {
  const root = mkdtempSync(join(tmpdir(), "setup-audit-all-explicit-"));
  writeFileSync(join(root, "CLAUDE.md"), claudeMdContent);
  return { root, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

// Mirrors what /setup writes when all five Schema L answers are explicitly
// supplied (autonomous + pre-baked path) — the canonical run #4 reproducer
// shape. branch_template populated, ## Docs present with all-true flags.
function allExplicitClaudeMd(): string {
  return [
    TOOLKIT_MARKER,
    "",
    "# Project",
    "",
    "## Task Tracking",
    "",
    "mode: linear",
    "mcp_server: linear",
    "branch_template: feat/{ticket-id}-{slug}",
    "",
    "### Linear",
    "",
    "team: STE",
    "project: DPT — Dev Process Toolkit",
    "",
    "## Docs",
    "",
    "user_facing_mode: true",
    "packages_mode: true",
    "changelog_ci_owned: true",
    "",
  ].join("\n");
}

// Mirrors a fully-autonomous run with no answers supplied — every value
// resolves to its mode-specific default, ## Docs all-false (per STE-107).
function allDefaultClaudeMd(): string {
  return [
    TOOLKIT_MARKER,
    "",
    "# Project",
    "",
    "## Task Tracking",
    "",
    "mode: linear",
    "mcp_server: linear",
    "branch_template: {type}/{ticket-id}-{slug}",
    "",
    "### Linear",
    "",
    "team: STE",
    "project: DPT — Dev Process Toolkit",
    "",
    "## Docs",
    "",
    "user_facing_mode: false",
    "packages_mode: false",
    "changelog_ci_owned: false",
    "",
  ].join("\n");
}

describe("STE-153 e2e (a) all-explicit — synthesize + probe → 0 violations", () => {
  test("synthesizes 4 user-supplied entries; probe runs clean", async () => {
    const ctx = makeProject(allExplicitClaudeMd());
    try {
      const claudeMdPath = join(ctx.root, "CLAUDE.md");
      const allUserSupplied: ResolvedSchemaLValues = {
        date: "2026-04-29",
        branchTemplate: { value: "feat/{ticket-id}-{slug}", reason: "user-supplied" },
        docsUserFacing: { value: true, reason: "user-supplied" },
        docsPackages: { value: true, reason: "user-supplied" },
        docsChangelogCi: { value: true, reason: "user-supplied" },
      };
      const r = synthesizeAuditSection(claudeMdPath, allUserSupplied);
      expect(r.synthesized).toBe(4);
      expect(r.skipped).toBe(0);

      const after = readFileSync(claudeMdPath, "utf-8");
      // Audit heading present + all four bullets carry user-supplied reason.
      expect(after).toContain("## /setup audit");
      expect(after.match(/reason:"user-supplied"/g)?.length).toBe(4);

      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("STE-153 e2e (b) all-default — byte-identical to v1.41.0 behaviour", () => {
  test("synthesizes 4 default-applied entries; probe runs clean; existing reason strings preserved", async () => {
    const ctx = makeProject(allDefaultClaudeMd());
    try {
      const claudeMdPath = join(ctx.root, "CLAUDE.md");
      const allDefault: ResolvedSchemaLValues = {
        date: "2026-04-29",
        branchTemplate: { value: "{type}/{ticket-id}-{slug}", reason: "default applied" },
        docsUserFacing: { value: false, reason: "default applied" },
        docsPackages: { value: false, reason: "default applied" },
        docsChangelogCi: { value: false, reason: "default applied" },
      };
      const r = synthesizeAuditSection(claudeMdPath, allDefault);
      expect(r.synthesized).toBe(4);
      expect(r.skipped).toBe(0);

      const after = readFileSync(claudeMdPath, "utf-8");
      expect(after).toContain("## /setup audit");
      // All four entries carry the existing reason string byte-for-byte.
      expect(after.match(/reason:"default applied"/g)?.length).toBe(4);
      expect(after.includes(`reason:"user-supplied"`)).toBe(false);

      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("STE-153 e2e (c) mixed — provenance preserved per resolution", () => {
  test("user-supplied branchTemplate + default-applied docs flags; probe runs clean", async () => {
    const ctx = makeProject(allExplicitClaudeMd());
    try {
      const claudeMdPath = join(ctx.root, "CLAUDE.md");
      const mixed: ResolvedSchemaLValues = {
        date: "2026-04-29",
        branchTemplate: { value: "feat/{ticket-id}-{slug}", reason: "user-supplied" },
        docsUserFacing: { value: false, reason: "default applied" },
        docsPackages: { value: false, reason: "default applied" },
        docsChangelogCi: { value: false, reason: "default applied" },
      };
      const r = synthesizeAuditSection(claudeMdPath, mixed);
      expect(r.synthesized).toBe(4);

      const after = readFileSync(claudeMdPath, "utf-8");
      expect(after.match(/reason:"user-supplied"/g)?.length).toBe(1);
      expect(after.match(/reason:"default applied"/g)?.length).toBe(3);

      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("STE-153 e2e (d) mode: none + 7c skip — branch_template absent, docs entries always emitted", () => {
  test("3 entries (no step:7c row); probe runs clean", async () => {
    // mode: none + 7c skip — branch_template is omitted from CLAUDE.md.
    // Docs section is always emitted (STE-107). The resolvedSchemaLValues
    // table omits the branchTemplate entry; synthesize produces 3 audit
    // entries; probe still passes because ## Docs is present.
    const claudeMd = [
      TOOLKIT_MARKER,
      "",
      "# Project",
      "",
      "## Docs",
      "",
      "user_facing_mode: false",
      "packages_mode: false",
      "changelog_ci_owned: false",
      "",
    ].join("\n");
    const ctx = makeProject(claudeMd);
    try {
      const claudeMdPath = join(ctx.root, "CLAUDE.md");
      const noBranch: ResolvedSchemaLValues = {
        date: "2026-04-29",
        docsUserFacing: { value: false, reason: "default applied" },
        docsPackages: { value: false, reason: "default applied" },
        docsChangelogCi: { value: false, reason: "default applied" },
      };
      const r = synthesizeAuditSection(claudeMdPath, noBranch);
      expect(r.synthesized).toBe(3);

      const after = readFileSync(claudeMdPath, "utf-8");
      // No step:7c row, three step:7d rows.
      expect(after).not.toMatch(/step:7c \(branch_template\)/);
      expect(after.match(/step:7d \(docs\./g)?.length).toBe(3);

      const report = await runSetupAuditSectionPresenceProbe(ctx.root);
      expect(report.violations).toEqual([]);
    } finally {
      ctx.cleanup();
    }
  });
});
