import { describe, expect, test } from "bun:test";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  SETUP_MARKER,
  detectManagedSignals,
  isToolkitManaged,
  type ManagedSignal,
} from "../adapters/_shared/src/toolkit_managed";

// STE-432 AC-STE-432.1 / AC-STE-432.8 — the single toolkit-managed predicate.
//
// One module answers "does the toolkit own this tree?" for every probe that
// used to open-code the question. Signal vocabulary is closed:
//   setup_marker         — the `/setup` generation marker
//   task_tracking_section — a real `## Task Tracking` level-2 heading
//   docs_section          — a real `## Docs` level-2 heading
//
// `isToolkitManaged` is true iff at least one NON-IGNORED signal is present.
// The `ignore` option exists so probe #18 can refuse to accept `## Docs` as
// evidence of managed-ness inside the probe that asserts `## Docs` exists.
//
// The helper NEVER throws: an absent, unreadable, or otherwise hostile
// CLAUDE.md returns `false` / `[]` (STE-394 precedent — a crashed gate is
// strictly worse than a failed one).

const isRoot = process.getuid?.() === 0;

function makeProject(claudeMd: string | null): { root: string; cleanup: () => void } {
  const root = mkdtempSync(join(tmpdir(), "toolkit-managed-"));
  if (claudeMd !== null) {
    writeFileSync(join(root, "CLAUDE.md"), claudeMd);
  }
  return { root, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

function sortedSignals(signals: readonly ManagedSignal[]): string[] {
  return [...signals].sort();
}

describe("AC-STE-432.1 — SETUP_MARKER is the single source of truth for the marker literal", () => {
  test("exports the exact `/setup` generation marker", () => {
    expect(SETUP_MARKER).toBe("<!-- generated by /dev-process-toolkit:setup -->");
  });
});

describe("AC-STE-432.1 — detectManagedSignals reports one entry per present signal", () => {
  test("marker only → exactly [setup_marker]", () => {
    const ctx = makeProject(`${SETUP_MARKER}\n\n# Project\n\nBody with no managed sections.\n`);
    try {
      expect(detectManagedSignals(ctx.root)).toEqual(["setup_marker"]);
      expect(isToolkitManaged(ctx.root)).toBe(true);
    } finally {
      ctx.cleanup();
    }
  });

  test("## Task Tracking only → exactly [task_tracking_section]", () => {
    const ctx = makeProject("# Project\n\n## Task Tracking\n\nmode: linear\n");
    try {
      expect(detectManagedSignals(ctx.root)).toEqual(["task_tracking_section"]);
      expect(isToolkitManaged(ctx.root)).toBe(true);
    } finally {
      ctx.cleanup();
    }
  });

  test("## Docs only → exactly [docs_section]", () => {
    const ctx = makeProject("# Project\n\n## Docs\n\nuser_facing_mode: false\n");
    try {
      expect(detectManagedSignals(ctx.root)).toEqual(["docs_section"]);
      expect(isToolkitManaged(ctx.root)).toBe(true);
    } finally {
      ctx.cleanup();
    }
  });

  test("all three signals → all three reported, no duplicates", () => {
    const body = [
      SETUP_MARKER,
      "",
      "# Project",
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "",
      "## Docs",
      "",
      "user_facing_mode: false",
      "",
    ].join("\n");
    const ctx = makeProject(body);
    try {
      const signals = detectManagedSignals(ctx.root);
      expect(signals.length).toBe(3);
      expect(sortedSignals(signals)).toEqual([
        "docs_section",
        "setup_marker",
        "task_tracking_section",
      ]);
    } finally {
      ctx.cleanup();
    }
  });

  test("hand-written CLAUDE.md with no managed signal → [] and false", () => {
    // The FR's reproduction case: a project that wrote its own CLAUDE.md.
    const ctx = makeProject("# Stock Check App\n\n## Tech Stack\n\nNext.js 15, Prisma.\n");
    try {
      expect(detectManagedSignals(ctx.root)).toEqual([]);
      expect(isToolkitManaged(ctx.root)).toBe(false);
    } finally {
      ctx.cleanup();
    }
  });

  test("a `## Documentation` heading is NOT the `## Docs` signal", () => {
    const ctx = makeProject("# Project\n\n## Documentation\n\nSee docs/.\n");
    try {
      expect(detectManagedSignals(ctx.root)).toEqual([]);
      expect(isToolkitManaged(ctx.root)).toBe(false);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-432.1 — absent or unreadable CLAUDE.md returns false without throwing", () => {
  test("absent CLAUDE.md → [] and false", () => {
    const ctx = makeProject(null);
    try {
      expect(detectManagedSignals(ctx.root)).toEqual([]);
      expect(isToolkitManaged(ctx.root)).toBe(false);
    } finally {
      ctx.cleanup();
    }
  });

  test("CLAUDE.md is a directory (EISDIR on read) → [] and false, no throw", () => {
    const ctx = makeProject(null);
    try {
      mkdirSync(join(ctx.root, "CLAUDE.md"));
      expect(() => detectManagedSignals(ctx.root)).not.toThrow();
      expect(detectManagedSignals(ctx.root)).toEqual([]);
      expect(isToolkitManaged(ctx.root)).toBe(false);
    } finally {
      ctx.cleanup();
    }
  });

  test.skipIf(isRoot)("chmod 000 CLAUDE.md (EACCES) → [] and false, no throw", () => {
    const ctx = makeProject(`${SETUP_MARKER}\n\n# Project\n\n## Task Tracking\n\nmode: linear\n`);
    try {
      chmodSync(join(ctx.root, "CLAUDE.md"), 0o000);
      expect(detectManagedSignals(ctx.root)).toEqual([]);
      expect(isToolkitManaged(ctx.root)).toBe(false);
    } finally {
      chmodSync(join(ctx.root, "CLAUDE.md"), 0o644);
      ctx.cleanup();
    }
  });
});

describe("AC-STE-432.1 — isToolkitManaged honours the `ignore` option", () => {
  test("docs-only tree is managed by default but NOT when docs_section is ignored", () => {
    const ctx = makeProject("# Project\n\n## Docs\n\nuser_facing_mode: false\n");
    try {
      expect(isToolkitManaged(ctx.root)).toBe(true);
      expect(isToolkitManaged(ctx.root, { ignore: ["docs_section"] })).toBe(false);
    } finally {
      ctx.cleanup();
    }
  });

  test("ignoring docs_section leaves the marker signal intact", () => {
    const ctx = makeProject(`${SETUP_MARKER}\n\n# Project\n\n## Docs\n\nuser_facing_mode: false\n`);
    try {
      expect(isToolkitManaged(ctx.root, { ignore: ["docs_section"] })).toBe(true);
    } finally {
      ctx.cleanup();
    }
  });

  test("ignoring docs_section leaves the ## Task Tracking signal intact", () => {
    const ctx = makeProject("# Project\n\n## Task Tracking\n\nmode: linear\n\n## Docs\n\nuser_facing_mode: false\n");
    try {
      expect(isToolkitManaged(ctx.root, { ignore: ["docs_section"] })).toBe(true);
    } finally {
      ctx.cleanup();
    }
  });

  test("ignoring every signal → false even on a fully managed tree", () => {
    const body = [
      SETUP_MARKER,
      "",
      "## Task Tracking",
      "",
      "mode: linear",
      "",
      "## Docs",
      "",
      "user_facing_mode: false",
      "",
    ].join("\n");
    const ctx = makeProject(body);
    try {
      expect(
        isToolkitManaged(ctx.root, {
          ignore: ["setup_marker", "task_tracking_section", "docs_section"],
        }),
      ).toBe(false);
    } finally {
      ctx.cleanup();
    }
  });

  test("an empty ignore list behaves exactly like no options at all", () => {
    const ctx = makeProject("# Project\n\n## Docs\n\nuser_facing_mode: false\n");
    try {
      expect(isToolkitManaged(ctx.root, { ignore: [] })).toBe(isToolkitManaged(ctx.root));
      expect(isToolkitManaged(ctx.root, { ignore: [] })).toBe(true);
    } finally {
      ctx.cleanup();
    }
  });
});

describe("AC-STE-432.8 — BOM and CRLF tolerance", () => {
  test("BOM + CRLF with `## Task Tracking` as the first line → exactly [task_tracking_section]", () => {
    const ctx = makeProject("\uFEFF## Task Tracking\r\n\r\nmode: linear\r\n");
    try {
      expect(detectManagedSignals(ctx.root)).toEqual(["task_tracking_section"]);
      expect(isToolkitManaged(ctx.root)).toBe(true);
    } finally {
      ctx.cleanup();
    }
  });

  test("CRLF-only file with a `## Docs` heading → exactly [docs_section]", () => {
    const ctx = makeProject("# Project\r\n\r\n## Docs\r\n\r\nuser_facing_mode: false\r\n");
    try {
      expect(detectManagedSignals(ctx.root)).toEqual(["docs_section"]);
    } finally {
      ctx.cleanup();
    }
  });

  test("BOM-prefixed marker line is still detected", () => {
    const ctx = makeProject(`\uFEFF${SETUP_MARKER}\r\n\r\n# Project\r\n`);
    try {
      expect(detectManagedSignals(ctx.root)).toEqual(["setup_marker"]);
      expect(isToolkitManaged(ctx.root)).toBe(true);
    } finally {
      ctx.cleanup();
    }
  });
});
