// bun_zero_match_placeholder — /gate-check probe (STE-113 AC-STE-113.4).
//
// Bun's `bun test` exits 1 when no test files match. Catches the regression
// where a Bun project loses its placeholder marker AND has no real tests,
// so the very first gate-check after `/setup` would fail.
//
// Vacuous when bun.lock is absent (non-Bun projects). Passes when either
//   (a) a real `*.test.ts` file exists outside node_modules, or
//   (b) a placeholder file with the marker comment exists.

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const MARKER = "Bun zero-match workaround";
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  ".cache",
  "dist",
  "build",
  "out",
  ".dpt-locks",
]);

export interface BunZeroMatchViolation {
  file: string;
  line: number;
  reason: string;
  note: string;
  message: string;
}

export interface BunZeroMatchReport {
  violations: BunZeroMatchViolation[];
}

interface ScanResult {
  hasTestFile: boolean;
  hasMarker: boolean;
}

function walkAndScan(dir: string, root: string, out: ScanResult, depth = 0): void {
  if (out.hasTestFile && out.hasMarker) return; // Early exit
  if (depth > 6) return; // Bound recursion to keep probe fast
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const name of entries) {
    if (SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      walkAndScan(full, root, out, depth + 1);
      continue;
    }
    if (!st.isFile()) continue;
    if (/\.test\.ts$/.test(name)) {
      // A `*.test.ts` file by itself satisfies the contract — but if it's
      // a placeholder file (carries the marker), we additionally record the
      // marker presence. Both are sufficient on their own.
      let content = "";
      try {
        content = readFileSync(full, "utf-8");
      } catch {
        // Treat unreadable as a real test file (existence is the check)
        out.hasTestFile = true;
        continue;
      }
      if (content.includes(MARKER)) {
        out.hasMarker = true;
        // Marker satisfies the contract — but also note any real test file.
      } else {
        out.hasTestFile = true;
      }
      continue;
    }
    // Allow the marker comment to live in a non-test source file too
    // (e.g., `src/_dpt_placeholder.ts`). Only scan plausible source files
    // (limited to TypeScript/JavaScript/Markdown) and bound the read size
    // so the probe stays fast on large projects.
    if (!/\.(ts|tsx|js|mjs|cjs|md)$/.test(name)) continue;
    if (st.size > 64 * 1024) continue; // skip large files; the marker is a 1-line top-of-file comment
    try {
      const content = readFileSync(full, "utf-8");
      if (content.includes(MARKER)) out.hasMarker = true;
    } catch {
      // ignore
    }
  }
}

export async function runBunZeroMatchPlaceholderProbe(
  projectRoot: string,
): Promise<BunZeroMatchReport> {
  const bunLock = join(projectRoot, "bun.lock");
  if (!existsSync(bunLock)) return { violations: [] };

  const scan: ScanResult = { hasTestFile: false, hasMarker: false };
  walkAndScan(projectRoot, projectRoot, scan);

  if (scan.hasTestFile || scan.hasMarker) return { violations: [] };

  const rel = relative(projectRoot, bunLock) || "bun.lock";
  const reason = `Bun project has no test files and no zero-match placeholder marker — \`bun test\` will exit 1 on the next gate`;
  const note = `${rel}:1 — ${reason}`;
  const message = [
    `bun_zero_match_placeholder: ${reason}`,
    `Remedy: write \`tests/.placeholder.test.ts\` carrying the marker comment ` +
      `\`// generated by /dev-process-toolkit:setup — Bun zero-match workaround (see examples/bun-typescript.md)\` ` +
      `until your project ships its first real test. ` +
      `Background: plugins/dev-process-toolkit/examples/bun-typescript.md § "Bun zero-match-exit-1 workaround".`,
    `Context: project=${projectRoot}, probe=bun_zero_match_placeholder`,
  ].join("\n");

  return {
    violations: [{ file: bunLock, line: 1, reason, note, message }],
  };
}
