// setup_bootstrap_committed — /gate-check probe (STE-109 AC-STE-109.7).
//
// If CLAUDE.md is toolkit-managed (`<!-- generated by /dev-process-toolkit:setup -->`)
// AND in the working tree, it MUST be committed. Catches the regression
// where /setup outputs leak into the first feature PR (smoke-test F7).
//
// Vacuous when CLAUDE.md is absent, the file is hand-written (no marker),
// or the project is not a git repository.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";

const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

export interface SetupBootstrapCommittedViolation {
  file: string;
  line: number;
  reason: string;
  note: string;
  message: string;
}

export interface SetupBootstrapCommittedReport {
  violations: SetupBootstrapCommittedViolation[];
}

function isGitRepo(projectRoot: string): boolean {
  return existsSync(join(projectRoot, ".git"));
}

function porcelainStatus(projectRoot: string, file: string): string {
  // Use the array form so the file argument is passed as an exec argv
  // entry rather than spliced into a shell command string. Eliminates the
  // shell quoting surface — a path with embedded `"` or shell metacharacters
  // can never reach a shell parser.
  try {
    const out = execFileSync("git", ["status", "--porcelain", "--", file], {
      cwd: projectRoot,
      encoding: "utf-8",
    });
    return out;
  } catch {
    return "";
  }
}

export async function runSetupBootstrapCommittedProbe(
  projectRoot: string,
): Promise<SetupBootstrapCommittedReport> {
  const claudeMd = join(projectRoot, "CLAUDE.md");
  if (!existsSync(claudeMd)) return { violations: [] };
  if (!isGitRepo(projectRoot)) return { violations: [] };

  const content = readFileSync(claudeMd, "utf-8");
  if (!content.includes(TOOLKIT_MARKER)) return { violations: [] };

  const status = porcelainStatus(projectRoot, "CLAUDE.md");
  if (status.length === 0) return { violations: [] }; // committed and unchanged

  // Status format: 2-char status + space + path. Untracked = `??`,
  // unstaged-modified = ` M`, staged-modified = `M `, etc.
  // Any non-empty output means the file is not in clean-committed state.
  const rel = relative(projectRoot, claudeMd);
  const reason = `${rel} is toolkit-managed but uncommitted (status: ${status.trim().slice(0, 2)}) — bootstrap commit missed`;
  const note = `${rel}:1 — ${reason}`;
  const message = [
    `setup_bootstrap_committed: ${reason}`,
    `Remedy: stage and commit the /setup output set as \`chore: bootstrap dev-process-toolkit (v<plugin-version>)\` (Phase 8 of skills/setup/SKILL.md). ` +
      `Files: CLAUDE.md, .claude/settings.json, .mcp.json (if tracker mode), specs/{requirements,technical-spec,testing-spec,plan/M1}.md, and the .gitkeep stubs in specs/frs{,/archive}/ + specs/plan/archive/.`,
    `Context: file=${rel}, marker=${TOOLKIT_MARKER}, probe=setup_bootstrap_committed`,
  ].join("\n");

  return {
    violations: [{ file: claudeMd, line: 1, reason, note, message }],
  };
}
