// setup_audit_section_presence — /gate-check probe (STE-108 AC-STE-108.6).
//
// If CLAUDE.md is toolkit-managed (`<!-- generated by /dev-process-toolkit:setup -->`)
// AND any default-applied step outcome is detectable in the file (Schema L
// `branch_template:` populated, `## Docs` flags emitted), the
// `## /setup audit` section MUST exist. Reading that section is the sole
// signal that a project was set up autonomously / with pre-baked answers.
//
// Vacuous pass when:
//   - CLAUDE.md is absent (no project to probe)
//   - The toolkit marker is absent (hand-written file, not /setup-managed)
//   - The toolkit marker is present but no default-applied outcomes are
//     visible (interactive run with no defaults)

import { existsSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";

const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";
const AUDIT_HEADING = "## /setup audit";

export interface SetupAuditSectionViolation {
  file: string;
  line: number;
  reason: string;
  note: string;
  message: string;
}

export interface SetupAuditSectionReport {
  violations: SetupAuditSectionViolation[];
}

/**
 * Exposed for cross-module reuse (STE-123 AC-STE-123.1) — /setup step 8a's
 * audit-section post-condition delegates to the same predicate this probe
 * uses at gate-check time. Single source of truth for the trigger condition
 * (Schema L `branch_template:` populated OR `## Docs` block present).
 */
export function hasDefaultApplicableOutcomes(content: string): boolean {
  // Default-applied step outcomes that must trigger an audit entry per
  // STE-108: branch_template (step 7c default) and any non-default
  // ## Docs flag (step 7d). Without one of these, the toolkit-managed
  // file could legitimately have been produced by a fully-interactive
  // run with no defaults.
  if (/^branch_template:\s*\S/m.test(content)) return true;
  if (/^##\s+Docs\b/m.test(content)) return true;
  return false;
}

export async function runSetupAuditSectionPresenceProbe(
  projectRoot: string,
): Promise<SetupAuditSectionReport> {
  const claudeMd = join(projectRoot, "CLAUDE.md");
  if (!existsSync(claudeMd)) return { violations: [] };

  const content = readFileSync(claudeMd, "utf-8");

  // Vacuous pass: hand-written file (no marker) is outside the probe's
  // scope — the audit-section invariant is /setup-managed only.
  if (!content.includes(TOOLKIT_MARKER)) return { violations: [] };

  // Vacuous pass: toolkit-managed but no default-applied outcomes to
  // require an audit trail for.
  if (!hasDefaultApplicableOutcomes(content)) return { violations: [] };

  // Required: the audit section.
  if (content.includes(AUDIT_HEADING)) return { violations: [] };

  const rel = relative(projectRoot, claudeMd);
  const reason = `${AUDIT_HEADING} section missing — toolkit-managed CLAUDE.md must record default-applied step outcomes`;
  const note = `${rel}:1 — ${reason}`;
  const message = [
    `setup_audit_section_presence: ${reason}`,
    `Remedy: append a ${AUDIT_HEADING} section to ${rel} naming the default-applied steps (step:7c branch_template, step:7d docs.* flags) — ` +
      `see plugins/dev-process-toolkit/adapters/_shared/src/setup/audit_log.ts:appendAuditEntry for the canonical bullet shape.`,
    `Context: file=${rel}, marker=${TOOLKIT_MARKER}, probe=setup_audit_section_presence`,
  ].join("\n");

  return {
    violations: [{ file: claudeMd, line: 1, reason, note, message }],
  };
}
