// toolkit_bootstrap_committed — /gate-check probe (STE-109 AC-STE-109.7,
// widened by STE-179 AC-STE-179.3 to cover the spec-files scope).
//
// If CLAUDE.md is toolkit-managed (`<!-- generated by /dev-process-toolkit:setup -->`),
// every toolkit-managed file in the working tree MUST be committed (no `??`
// or modification status in `git status --porcelain`).
//
// Toolkit-managed scan-set:
//   - CLAUDE.md
//   - .claude/settings.json (if present)
//   - .mcp.json (if present)
//   - specs/requirements.md (if present)
//   - specs/technical-spec.md (if present)
//   - specs/testing-spec.md (if present)
//   - specs/plan/M*.md (every active plan file, if specs/plan/ exists)
//   - specs/frs/*.md (every active FR file, if specs/frs/ exists; archive/ excluded)
//
// `/setup` produces the bootstrap commit covering CLAUDE.md + settings + mcp;
// `/spec-write` produces the spec commit (STE-179 Step 7a) covering specs;
// `/implement` produces the feature commit. Each skill owns its diff.
//
// Vacuous when CLAUDE.md is absent, the file is hand-written (no marker), or
// the project is not a git repository.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const TOOLKIT_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

export interface ToolkitBootstrapCommittedViolation {
  file: string;
  line: number;
  reason: string;
  note: string;
  message: string;
}

export interface ToolkitBootstrapCommittedReport {
  violations: ToolkitBootstrapCommittedViolation[];
}

function isGitRepo(projectRoot: string): boolean {
  return existsSync(join(projectRoot, ".git"));
}

function porcelainStatus(projectRoot: string, file: string): string {
  // Use the array form so the file argument is passed as an exec argv entry
  // rather than spliced into a shell command string. Eliminates the shell
  // quoting surface — a path with embedded `"` or shell metacharacters can
  // never reach a shell parser.
  try {
    const out = execFileSync("git", ["status", "--porcelain", "--", file], {
      cwd: projectRoot,
      encoding: "utf-8",
    });
    return out;
  } catch {
    return "";
  }
}

function listMdFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  try {
    return readdirSync(dir)
      .filter((name) => name.endsWith(".md") && !name.startsWith("."))
      .filter((name) => {
        const full = join(dir, name);
        try {
          return statSync(full).isFile();
        } catch {
          return false;
        }
      })
      .map((name) => join(dir, name));
  } catch {
    return [];
  }
}

function buildScanSet(projectRoot: string): string[] {
  const candidates: string[] = [];
  const claudeMd = join(projectRoot, "CLAUDE.md");
  if (existsSync(claudeMd)) candidates.push(claudeMd);

  const settings = join(projectRoot, ".claude", "settings.json");
  if (existsSync(settings)) candidates.push(settings);

  const mcp = join(projectRoot, ".mcp.json");
  if (existsSync(mcp)) candidates.push(mcp);

  const specsDir = join(projectRoot, "specs");
  if (existsSync(specsDir)) {
    for (const name of ["requirements.md", "technical-spec.md", "testing-spec.md"]) {
      const p = join(specsDir, name);
      if (existsSync(p)) candidates.push(p);
    }
    candidates.push(...listMdFiles(join(specsDir, "plan")));
    candidates.push(...listMdFiles(join(specsDir, "frs")));
  }
  return candidates;
}

function buildMessage(
  filePath: string,
  projectRoot: string,
  status: string,
): { reason: string; note: string; message: string } {
  const rel = relative(projectRoot, filePath);
  const trimmed = status.trim().slice(0, 2);
  const reason = `${rel} is toolkit-managed but uncommitted (status: ${trimmed}) — toolkit bootstrap commit missed`;
  const note = `${rel}:1 — ${reason}`;
  const message = [
    `toolkit_bootstrap_committed: ${reason}`,
    `Remedy: stage and commit the appropriate toolkit-managed file. Owner skill by file: CLAUDE.md / .claude/settings.json / .mcp.json ⇒ \`/setup\` bootstrap (Phase 8b); specs/* ⇒ \`/spec-write\` (Step 7a — \`chore(specs): write FR <id>\` or \`docs(specs): edit cross-cutting specs\`); per-FR feature files ⇒ \`/implement\` Phase 4 step 15.`,
    `Context: file=${rel}, marker=${TOOLKIT_MARKER}, probe=toolkit_bootstrap_committed`,
  ].join("\n");
  return { reason, note, message };
}

export async function runToolkitBootstrapCommittedProbe(
  projectRoot: string,
): Promise<ToolkitBootstrapCommittedReport> {
  const claudeMd = join(projectRoot, "CLAUDE.md");
  if (!existsSync(claudeMd)) return { violations: [] };
  if (!isGitRepo(projectRoot)) return { violations: [] };

  const claudeContent = readFileSync(claudeMd, "utf-8");
  if (!claudeContent.includes(TOOLKIT_MARKER)) return { violations: [] };

  const scanSet = buildScanSet(projectRoot);
  const violations: ToolkitBootstrapCommittedViolation[] = [];

  for (const filePath of scanSet) {
    const status = porcelainStatus(projectRoot, filePath);
    if (status.length === 0) continue; // committed and unchanged
    const { reason, note, message } = buildMessage(filePath, projectRoot, status);
    violations.push({ file: filePath, line: 1, reason, note, message });
  }

  return { violations };
}
