// toolkit_managed — the single implementation of the "does the toolkit own this
// tree?" predicate (M118 STE-432 AC-STE-432.1 / AC-STE-432.8).
//
// Four probes used to open-code the same question against `CLAUDE.md`, each
// with its own marker literal and its own heading regexes, which is how the
// answers drifted apart. This module is now the one place that decides, and the
// signal vocabulary is closed:
//
//   setup_marker          — the `/setup` generation marker (`SETUP_MARKER`)
//   task_tracking_section — a real `## Task Tracking` level-2 heading
//   docs_section          — a real `## Docs` level-2 heading
//
// Consumers:
//   * probe #18 `claudemd-docs-section-present` (`./claudemd_docs_section.ts`) —
//     calls `isToolkitManaged(root, { ignore: ["docs_section"] })`. The `ignore`
//     option exists FOR this caller: the probe asserts that `## Docs` is
//     present, so accepting `## Docs` as the evidence that the tree is managed
//     would make the probe circular (and vacuous on exactly the trees it is
//     meant to catch).
//   * probe #69 `upgrade_staleness` (`./upgrade_staleness.ts`) — Step 0's
//     applicability short-circuit, all three signals in play.
//   * probes #19 `setup-audit-section-presence` and #22
//     `toolkit-bootstrap-committed` — marker-only membership, expressed as
//     `detectManagedSignals(root).includes("setup_marker")` rather than a
//     re-declared string literal.
//
// Contract notes:
//   * SYNCHRONOUS (`readFileSync`). All four consumers do synchronous file IO
//     throughout, and no consumer body awaits anything today — the `async`
//     keyword on the four `run*Probe` functions is signature convention, not
//     concurrency. An `fs/promises` predicate would introduce the first `await`
//     into four otherwise-synchronous bodies for no gain.
//   * NEVER THROWS. An absent, unreadable (EACCES) or is-a-directory (EISDIR)
//     `CLAUDE.md` all yield `[]` / `false`. STE-394 precedent: a crashed gate is
//     strictly worse than a failed one — a FAILED verdict is a verdict, a crash
//     is no verdict at all.
//   * PURE. No child processes, no network, no writes, no logging — probe #69
//     imports this module and its suite asserts source purity on the importer.
//   * Detection reads the RAW file body: HTML comments are NOT stripped, because
//     `SETUP_MARKER` *is* an HTML comment. Probe #18 strips comments on its own
//     assertion side only, where a commented-out `## Docs` must not count.
//   * BOM and CRLF are normalized BEFORE the line-anchored heading matches, so a
//     Windows-authored `CLAUDE.md` whose first line is a managed heading is
//     still recognized (AC-STE-432.8).

import { readFileSync } from "node:fs";
import { join } from "node:path";

/** The `/setup` generation marker — the strongest managed-tree signal. */
export const SETUP_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

/** The closed vocabulary of toolkit-managed signals. */
export type ManagedSignal = "setup_marker" | "task_tracking_section" | "docs_section";

/**
 * Signal detectors in the order `detectManagedSignals` reports them. The order
 * is part of the contract (callers compare arrays), so it is declared once here
 * rather than being an accident of control flow.
 *
 * The heading patterns preserve probe #69's existing semantics byte for byte —
 * `^##\s+<Name>\s*$` under `m` — so a `## Documentation` heading is NOT the
 * `## Docs` signal.
 */
const DETECTORS: readonly { signal: ManagedSignal; test: (body: string) => boolean }[] = [
  { signal: "setup_marker", test: (body) => body.includes(SETUP_MARKER) },
  { signal: "task_tracking_section", test: (body) => /^##\s+Task Tracking\s*$/m.test(body) },
  { signal: "docs_section", test: (body) => /^##\s+Docs\s*$/m.test(body) },
];

/** Options for {@link isToolkitManaged}. */
export interface IsToolkitManagedOptions {
  /**
   * Signals that must NOT count as evidence of managed-ness. Absent or empty
   * behaves identically to no options at all.
   */
  ignore?: readonly ManagedSignal[];
}

/**
 * Strip a leading UTF-8 BOM and fold CRLF (and lone CR) to LF.
 *
 * Without this a BOM glued to the first line defeats `^` and a trailing `\r`
 * defeats `$`, so a Windows-authored managed file reads as hand-written — the
 * silent false-negative AC-STE-432.8 pins.
 */
function normalize(body: string): string {
  const withoutBom = body.charCodeAt(0) === 0xfeff ? body.slice(1) : body;
  return withoutBom.replace(/\r\n?/g, "\n");
}

/**
 * Read `<projectRoot>/CLAUDE.md`, returning `null` on any failure.
 *
 * Every read error collapses to the same answer — missing, unreadable, and
 * is-a-directory are all "the toolkit cannot see a managed file here". Catching
 * is side-effect free: no logging, no rethrow.
 */
function readClaudeMd(projectRoot: string): string | null {
  try {
    return readFileSync(join(projectRoot, "CLAUDE.md"), "utf-8");
  } catch {
    return null;
  }
}

/**
 * Every toolkit-managed signal present in `<projectRoot>/CLAUDE.md`, in
 * `DETECTORS` order, without duplicates.
 *
 * Returns `[]` — never throws — when `CLAUDE.md` is absent or unreadable.
 *
 * @param projectRoot absolute path to the consumer project root
 */
export function detectManagedSignals(projectRoot: string): ManagedSignal[] {
  const raw = readClaudeMd(projectRoot);
  if (raw === null) return [];
  const body = normalize(raw);
  return DETECTORS.filter((d) => d.test(body)).map((d) => d.signal);
}

/**
 * True iff at least one NON-IGNORED managed signal is present.
 *
 * @param projectRoot absolute path to the consumer project root
 * @param opts `ignore` lists signals that do not count as evidence; an absent
 *   or empty list behaves exactly like no options at all
 */
export function isToolkitManaged(
  projectRoot: string,
  opts?: IsToolkitManagedOptions,
): boolean {
  const ignore = opts?.ignore ?? [];
  return detectManagedSignals(projectRoot).some((s) => !ignore.includes(s));
}
