// M109 STE-394 AC-STE-394.1..5 — the /gate-check probe `upgrade_staleness` (#69).
//
// A warn-only advisory probe: it walks the migration registry's detectors and
// renders one row per consumer artifact that has fallen behind current toolkit
// conventions. It NEVER emits GATE FAILED — pre-existing drift must not block a
// merge, so `violations` is always empty and every finding lands under
// GATE PASSED WITH NOTES.
//
// Step 0 (applicability short-circuit) mirrors `skills/upgrade/SKILL.md`: a tree
// whose `CLAUDE.md` carries no toolkit-managed section was never bootstrapped,
// so there is usually no legacy state to report — only an absent install. That
// path skips the registry walk, running ONLY the STE-410 monolith-split sniff:
// a pre-toolkit tree with a monolithic `specs/requirements.md` still earns a
// /setup-then-/upgrade nudge (closed by LEGACY_MONOLITH_HINT), and every other
// unmanaged tree returns clean. Leaving the rest of the registry unwalked is what
// keeps the probe silent (and cheap) on hand-written trees the toolkit does not own.
//
// Shape precedent: `runMigrationCoverageProbe` (`./migrations/coverage.ts`) —
// pure file reads plus a registry module load. No git, no network, no LLM
// judgment, no writes.
//
// Degrade-to-row (hardening): a detector reads consumer files, so it CAN throw
// on a tree the toolkit does not control — an unreadable root `.gitignore`
// (chmod 000) makes `m104-legacy-state` throw EACCES, for instance. An
// unguarded throw would propagate out of the probe and crash the whole gate
// run, which is strictly worse than the GATE FAILED this probe forbids: a
// FAILED verdict is a verdict, a crashed gate is no verdict at all. So every
// `detect` call is guarded INDIVIDUALLY and a throw degrades to a row rather
// than to a crash:
//   * the probe still resolves, and `violations` stays empty — degrade, never
//     escalate;
//   * the failure is never silent — the erroring entry renders inside the same
//     byte-pinned `<id> (<version>): <evidence>` shape, with the thrown message
//     collapsed to one line and carried as the evidence text, so the operator
//     can see which entry broke and why;
//   * one throwing entry never suppresses its neighbours — the walk continues
//     in registry order, and healthy entries render exactly as they would with
//     no throwing sibling.
// Catching is side-effect free: no logging, no git, no network — the purity
// contract (AC-STE-394.3) holds on the error path too.

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { MIGRATIONS, type DetectResult, type MigrationEntry } from "./migrations/index";
import { monolithSplit } from "./migrations/monolith_split";

/** The probe's stable id, as registered in `skills/gate-check/SKILL.md`. */
export const PROBE_ID = "upgrade_staleness";

/**
 * Byte-pinned closing line of the NOTES block. `/upgrade` carries
 * `user-invocable: false`, so the remedy says so rather than sending an
 * operator hunting for a slash-menu entry that is not there.
 */
export const UPGRADE_STALENESS_REMEDY =
  "Remedy: run /dev-process-toolkit:upgrade to apply these migrations (Claude can invoke it; it is not on the slash menu).";

/**
 * Byte-pinned closing NOTES line for the unmanaged-tree legacy-monolith
 * carve-out. It routes to `/setup` FIRST because `/upgrade` Step 0 refuses an
 * unmanaged tree: bootstrap the toolkit-managed sections, THEN split the
 * monolithic `specs/requirements.md` into per-FR files with `/upgrade`.
 */
export const LEGACY_MONOLITH_HINT =
  "legacy monolithic specs detected — run /dev-process-toolkit:setup to bootstrap, then /dev-process-toolkit:upgrade to split specs/requirements.md into per-FR files.";

/** The `/setup` generation marker — the strongest managed-tree signal. */
const SETUP_MARKER = "<!-- generated by /dev-process-toolkit:setup -->";

/** Managed level-2 sections that also mark a tree as toolkit-owned. */
const MANAGED_SECTIONS: readonly RegExp[] = [
  /^##\s+Task Tracking\s*$/m,
  /^##\s+Docs\s*$/m,
];

export interface UpgradeStalenessReport {
  /** One byte-pinned row per applying entry, in registry order. */
  rows: string[];
  /** The rendered NOTES block: `[...rows, REMEDY]`, or `[]` with zero rows. */
  notes: string[];
  /** ALWAYS empty — the probe never FAILs the gate. */
  violations: never[];
}

/**
 * Step 0 — is this tree toolkit-managed? True when `CLAUDE.md` exists AND
 * carries the `/setup` generation marker or a managed section. An absent or
 * unreadable `CLAUDE.md`, and a hand-written one with neither signal, are both
 * out of scope: never migrate a file the toolkit does not own.
 */
async function isToolkitManaged(projectRoot: string): Promise<boolean> {
  let body: string;
  try {
    body = await readFile(join(projectRoot, "CLAUDE.md"), "utf-8");
  } catch {
    return false;
  }
  if (body.includes(SETUP_MARKER)) return true;
  return MANAGED_SECTIONS.some((re) => re.test(body));
}

/**
 * Evidence text for an entry whose detector threw — one line, never empty, and
 * never the string `"undefined"`.
 *
 * A thrown non-Error (a bare string, or anything at all) must still read as a
 * diagnosis, so the message is extracted by VALUE TYPE rather than by reaching
 * for `.message` on something that may not have one. Whitespace collapses to
 * single spaces because a raw multi-line dump (a stack, say) would break the
 * NOTES block's one-row-per-line shape.
 */
function describeDetectorFailure(thrown: unknown): string {
  let raw: string;
  if (thrown instanceof Error) {
    raw = thrown.message;
  } else if (typeof thrown === "string") {
    raw = thrown;
  } else if (thrown === undefined || thrown === null) {
    raw = "";
  } else {
    // A value with a hostile `toString` must not turn the guard into a new throw.
    try {
      raw = String(thrown);
    } catch {
      raw = "";
    }
  }
  const oneLine = raw.replace(/\s+/g, " ").trim();
  return `detector error: ${oneLine === "" ? "detector threw a value with no message" : oneLine}`;
}

/**
 * The byte-pinned row shape, `<entry-id> (<introduced_in>): <evidence joined by
 * "; ">`, in exactly one place. Both the managed registry walk and the
 * unmanaged-tree monolith sniff (STE-410) render through here, so the byte shape
 * cannot drift between the two paths.
 */
function renderRow(entry: MigrationEntry, evidence: readonly string[]): string {
  return `${entry.id} (${entry.introduced_in}): ${evidence.join("; ")}`;
}

/**
 * Walk the migration registry and report every entry whose legacy state is
 * still present on disk.
 *
 * Rows render as `<entry-id> (<introduced_in>): <evidence joined by "; ">`,
 * with the evidence in the detector's returned order — never re-sorted, never
 * truncated. Non-applying entries render nothing. The remedy closes the NOTES
 * block exactly once per run, and only when at least one row rendered.
 *
 * Call site: `/gate-check` probe #69 + `tests/gate-check-upgrade-staleness.test.ts`.
 *
 * @param projectRoot absolute path to the consumer project root
 * @param registry the migration registry to walk; defaults to live `MIGRATIONS`
 */
export async function runUpgradeStalenessProbe(
  projectRoot: string,
  registry: readonly MigrationEntry[] = MIGRATIONS,
): Promise<UpgradeStalenessReport> {
  // Step 0 — short-circuit BEFORE the registry walk. STE-410 carves ONE
  // exception: on an unmanaged tree the probe runs ONLY the monolith-split
  // sniff (the rest of the registry stays unwalked). When it applies, the row
  // is closed by LEGACY_MONOLITH_HINT rather than the registry remedy; a
  // throwing detector degrades to silence (never a crash, never GATE FAILED).
  if (!(await isToolkitManaged(projectRoot))) {
    try {
      const d = monolithSplit.detect(projectRoot);
      if (d.applies) {
        const row = renderRow(monolithSplit, d.evidence);
        return { rows: [row], notes: [row, LEGACY_MONOLITH_HINT], violations: [] };
      }
    } catch {
      /* degrade to silence — the sniff throwing must not FAIL the gate */
    }
    return { rows: [], notes: [], violations: [] };
  }

  const rows: string[] = [];
  for (const entry of registry) {
    let detected: DetectResult;
    try {
      detected = entry.detect(projectRoot);
    } catch (thrown) {
      // Degrade to a row, never to a crash — and keep walking, so one broken
      // detector cannot silence the entries behind it.
      rows.push(renderRow(entry, [describeDetectorFailure(thrown)]));
      continue;
    }
    if (!detected.applies) continue;
    rows.push(renderRow(entry, detected.evidence));
  }

  return {
    rows,
    notes: rows.length > 0 ? [...rows, UPGRADE_STALENESS_REMEDY] : [],
    violations: [],
  };
}
